"""Rebuild selected standalone terrain assets, preserving Godot world layout.

Usage: blender -b --python blender/rebuild_terrain_modules.py -- 0,-1 0,0
Each module gets its own native .blend, local origin, GLB and collision refresh
entry. No world scene or placement file is generated by this command.
"""
from pathlib import Path
import sys,json,math,bpy,numpy as np
ROOT=Path('D:/test6');sys.path.insert(0,str(ROOT/'blender'))
import world_definition as W
import terrain_topology as T
sys.path.insert(0,str(ROOT/"captures"))
import cliff_sections_10c
args=sys.argv[sys.argv.index('--')+1:]
cells=[(x,z) for z in range(W.BOUNDS[2],W.BOUNDS[3]+1) for x in range(W.BOUNDS[0],W.BOUNDS[1]+1)] if '--all' in args else [tuple(map(int,s.split(','))) for s in args]
native=ROOT/'captures';native.mkdir(exist_ok=True)
def linear(c):return np.where(c<=.04045,c/12.92,((c+.055)/1.055)**2.4)
updates=[]
for cx,cz in cells:
    bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
    vertices,faces=T.chunk_mesh(cx,cz);tris=vertices[faces]
    centers=tris.mean(axis=1)+[cx*768,0,cz*768]
    normals=np.cross(tris[:,1]-tris[:,0],tris[:,2]-tris[:,0]);normals/=np.maximum(np.linalg.norm(normals,axis=1)[:,None],1e-8)
    variation=np.mod(np.sin(centers[:,0]*12.9898+centers[:,2]*78.233)*43758.5453,1)
    colors=linear(np.asarray([W.terrain_color(c,n,v) for c,n,v in zip(centers,normals,variation)]))
    name=f'Ground_{cx}_{cz}'
    mesh=bpy.data.meshes.new(name+'Geometry');mesh.from_pydata(np.c_[vertices[:,0],-vertices[:,2],vertices[:,1]],[],faces);mesh.update()
    attr=mesh.color_attributes.new(name='Palette',type='FLOAT_COLOR',domain='CORNER')
    attr.data.foreach_set('color',np.repeat(np.c_[colors,np.ones(len(colors))],3,axis=0).astype(np.float32).ravel())
    mesh.color_attributes.active_color_index=0;mesh.color_attributes.render_color_index=0
    mat=bpy.data.materials.new('Meadow stone and shore');mat.use_nodes=True
    node=mat.node_tree.nodes.new('ShaderNodeVertexColor');node.layer_name='Palette'
    bsdf=mat.node_tree.nodes.get('Principled BSDF');bsdf.inputs['Roughness'].default_value=1
    mat.node_tree.links.new(node.outputs['Color'],bsdf.inputs['Base Color']);mesh.materials.append(mat)
    obj=bpy.data.objects.new(name,mesh);bpy.context.scene.collection.objects.link(obj)
    obj.asset_mark();obj['terrain_cell']=[cx,cz];obj['assembly']='Placed independently in Godot World/Terrain'
    obj.select_set(True);bpy.context.view_layer.objects.active=obj
    path='captures/round-10c-'+name+'.glb'
    bpy.ops.export_scene.gltf(filepath=str(ROOT/path),export_format='GLB',use_selection=True,export_apply=True,export_vertex_color='ACTIVE')
    bpy.ops.wm.save_as_mainfile(filepath=str(native/('round-10c-'+name+'.blend')))
    updates.append({'name':name,'path':path,'cell':[cx,cz],'triangles':len(faces)})
    print('UPDATED TERRAIN MODULE',name,len(faces),flush=True)
(ROOT/'captures/round-10c-terrain-updates.json').write_text(json.dumps(updates,indent=2))
