from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[1];sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text(encoding='utf-8'))
ind=R/'reviews/round-29e-island-independent-review.md';assert ind.exists()
s=(R/'captures/checkpoint_islands_29ab.py').read_text();start=s.index('runs=');end=s.index('\nfor label',start)
s=s[:start]+"runs={'29e':'lantern-island-29e-20260908T173424Z-b8920ba894e247bd9057f06b160a3ce1'}"+s[end:];exec(compile(s,str(__file__),'exec'))
run=R/'captures/validation_runs/lantern-island-29e-20260908T173424Z-b8920ba894e247bd9057f06b160a3ce1';out=read(R/'reviews/round-29e-root-evidence.json');d=read(run/'images/night-reference.png.json')
out.update(reason='Upper wall locally segmented; retained progress but land mass remains too tall/wide relative to lighthouse and continuous tidal bands remain. Next prioritize physical land/building proportions, then shoreline topology. Pixel intervals are manual projection observations, not precise3D dimensions.',root_directly_viewed_measurement_crops=True)
(R/'reviews/round-29e-root-evidence.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
registry=read(R/'reviews/reference-view-1342-progress-29c.json')
registry.update(run_id=d['run_id'],camera=d['camera'],reference_image=out['root_views'][0],final_lantern_configuration=d['lantern_lighting'],geometry_basis={'islands':'A/B20l; C/D29e native connected terrain/road and irregular core; next correct land/building proportions','lighthouse':'19h native','harbor':'22g','village_and_headland':'26b','production':'17e/18c/19h unchanged'},evidence=['reviews/round-29-worklog.md','reviews/round-29e-root-evidence.json','reviews/round-29e-island-independent-review.md','reviews/round-29e-independent-geometry.json','reviews/round-29e-planning-notes.md'],remaining=['Correct C/D land height/width relative to unchanged native building sizes using fixed reference camera; rebuild occupied-site pads and re-drape paths, trees, buildings, collisions','Correct keeper-house side/orientation inD; source reference house right of tower, current left; verify with actual next render','Break continuous tidal edges with actual shoreline/midsection topology after proportions, not more long wedges or globally smoothed skirts','All20 references plus opening, weather/time, warm water/light, clouds, mainland/villages and flying-space observation remain incomplete'])
(R/'reviews/reference-view-1342-progress-29e.json').write_text(json.dumps(registry,ensure_ascii=False,indent=2),encoding='utf-8')
note=f'**最新29e C/D地表与道路联动改形完成五GPU及独立审查，整体仍需返工。** 234塔屋/树根支承面保持，223显著地表点变化，实际道路贴地44.9986–45.0014mm、最大坡9.6545°；29d三处侧带投影反折消除，局部错位岩肩可保留。{out["binding_count"]}冻结绑定SHA核对，61落点差最大0.1984mm、基础抽样差0.1221mm。**下一步优先纠正C/D陆体相对建筑的高度/宽度，再改岸线断裂拓扑。** 独立人工投影复核显示岛身偏高偏宽，不能把像素比当精确3D缩放值；保持建筑原生尺度，重做合适pad并联动重贴道路/树/建筑与派生碰撞。参考中央守塔屋在塔右，本版塔左，也需校正D朝向/布置。原18岸线/旧61落点是候选设计，不是永久用户约束；其他区域不变。所有29d/e建模、重开、GPU进程已结束，不重启旧失败运行。接续 `reviews/round-29-worklog.md`、`reviews/round-29e-island-independent-review.md`、`reviews/reference-view-1342-progress-29e.json`。生产17e/18c/19h未改；全部20参考及原图Goal active。'
for name in ['WORKSPACE_RESUME.md','reviews/LOOP.md']:
 p=R/name;s=p.read_text(encoding='utf-8');assert '**最新29e C/D地表' not in s;first,rest=s.split('\n',1);p.write_text(first+'\n\n'+note+'\n'+rest,encoding='utf-8')
for name in ['REFERENCE_SCENES.md','WORLD_SCENE_PLAN.md']:
 p=R/name;s=p.read_text(encoding='utf-8');assert '29e岛体比例接续' not in s;p.write_text(s+'\n\n29e岛体比例接续：234占用支承区保护下地表/道路实际联动改形，五GPU/独立完成，局部错位可保留但总体仍失败。下一步先改C/D陆体相对原生建筑比例及D守塔屋侧向布置，再改岸线/中段实体拓扑；具体人工投影区间与限制见 `reviews/round-29e-island-independent-review.md`，最新证据登记 `reviews/reference-view-1342-progress-29e.json`。旧18岸线与候选落点不构成不可变约束，所有实际受影响支承/路/散布/碰撞要同步。生产未改，完整Goal active。\n',encoding='utf-8')
p=R/'reviews/round-29-worklog.md';s=p.read_text(encoding='utf-8').replace('## 29e：联动道路与岩肩，等待五GPU造型','## 29e：联动道路与岩肩实拍完成，下一步先校正陆体比例')
s=s.replace('GPU run `lantern-island-29e-20260908T173424Z-b8920ba894e247bd9057f06b160a3ce1`，root4329正在运行；必须查询实际句柄，不因观察超时重启。待根与独立看完五图后更新接续结论。全部29d及29e原生建模/重开进程均已结束。',f'GPU run `lantern-island-29e-20260908T173424Z-b8920ba894e247bd9057f06b160a3ce1` terminal passed，root4329终止；根/独立直接看完五原图，{out["binding_count"]}绑定SHA核对。61落点最大差0.1984mm、9×9基础抽样差0.1221mm。局部上台凹缝/斜肩真实改善，但陆体过于高宽，水线层带仍连续，整体打回。全部29d/e原生/GPU均终止。')
s+='\n\n## 29e之后的优先接续：比例与构图\n\n根与独立直接看参考和实际原像素裁片。独立人工区间：参考塔尖Y546–550、塔脚623–627、近岩水线701–708、含礁宽X835–1100；29e相应535–539、622–628、750–760、X837–1230。参考约640下层草台不是塔体脚。塔体屏高略有差异而相近，陆体相对塔明显过高过宽；这是投影观察，不是准确3D尺寸或缩放系数。裁片及尺度见最终独立报告，原PNG未修改。另参考守塔屋在塔右、候选在塔左，下一稿要校正D的朝向或布局。\n\n以保存29e源为建模接续。保持原生灯塔/守塔屋尺寸，先做较低、较紧凑陆体的Blender候选；缩放后原pad会一起变小，必须按真实建筑足印重新扩大/修整支承，再让路径和树屋塔按新面贴地，生成同版网格碰撞。不要直接给物理根节点非均匀缩放后就假设支承仍通过。用固定1342机位比较比例；允许合理修改C/D候选位置/朝向并记录设计依据，不改镜头掩盖比例问题。C/D原61落点中受影响项需要对比设计后的实际值，不能沿用“全部旧位置完全不变”门禁阻止目标修正；A/B及其他未改区域继续核对保持。\n\n比例方向确认后，再在非支承区改XY岸缘和中段拓扑，构成短凹湾、错位露头、接入潮间根的短岩肩，打断连续薄带；不要再次冻结18岸线并仅全局平滑或加长楔。最新登记 `reference-view-1342-progress-29e.json`，完整20参考Goal active。\n'
p.write_text(s,encoding='utf-8');print('29e final checkpoint; Goal active')
