from pathlib import Path
import json,math,hashlib,numpy as np
R=Path(__file__).resolve().parents[1];src=R/'captures/rightcoast33-native-intake.json';native=json.loads(src.read_text(encoding='utf-8'));run=R/'captures/validation_runs/foreground-island-32f-20260908T224143Z-7598ab628ffa40f0a4f20816ba9f05e2';scene=json.loads((run/'images/day-reference.png.json').read_text(encoding='utf-8'));cam=scene['camera'];pitch,yaw,roll=cam['rotation'];assert abs(roll)<1e-7
cy,sy=math.cos(yaw),math.sin(yaw);cx,sx=math.cos(pitch),math.sin(pitch);B=np.array([[cy,sy*sx,sy*cx],[0,cx,-sx],[-sy,cy*sx,cy*cx]]);origin=np.array([-2180,0,-1830]);wc=np.array(cam['position'])-origin;camera=wc[[0,2,1]]*np.array([1,-1,1]);f=941/(2*math.tan(math.radians(cam['fov']/2)));meshes={k:np.array(v['vertices'])[np.array(v['triangles'])] for k,v in native['objects'].items()};results=[]
for pixel in [(1305,815),(1342,856),(1465,755),(1375,585),(1490,596),(1550,568),(1650,554),(1520,628)]:
 px,py=pixel;g=B@np.array([(px-836)/f,-(py-470.5)/f,-1]);direction=np.array([g[0],-g[2],g[1]]);direction/=np.linalg.norm(direction);hits=[]
 for name,ts in meshes.items():
  e1=ts[:,1]-ts[:,0];e2=ts[:,2]-ts[:,0];p=np.cross(direction,e2);det=np.einsum('ij,ij->i',e1,p);inv=np.divide(1.,det,out=np.zeros_like(det),where=np.abs(det)>1e-10);t=camera-ts[:,0];u=np.einsum('ij,ij->i',t,p)*inv;q=np.cross(t,e1);v=q@direction*inv;ds=np.einsum('ij,ij->i',e2,q)*inv;ids=np.where((abs(det)>1e-10)&(u>=-1e-7)&(v>=-1e-7)&(u+v<=1+1e-7)&(ds>0))[0]
  if not len(ids):continue
  i=int(ids[np.argmin(ds[ids])]);loc=camera+direction*ds[i];normal=np.cross(e1[i],e2[i]);normal/=np.linalg.norm(normal);world=origin+loc[[0,2,1]]*np.array([1,1,-1]);hits.append(dict(object=name,triangle=i,triangle_xyz=ts[i].tolist(),location_blender=loc.tolist(),location_world=world.tolist(),normal_blender=normal.tolist(),distance_m=float(ds[i])))
 hits.sort(key=lambda x:x['distance_m']);results.append(dict(pixel=list(pixel),nearest_headland_hit=hits[0] if hits else None))
out=dict(scope='Read-only fixed32f main camera rays to current26b headland source meshes. Selected pixels were viewed in day-reference. This reports source hits only; does not include roofs, trees, paving or original World occluders, and does not infer protected areas from a point. Before editing intersect complete proposed faces/neighborhood with real9house/922paving/trees.',source_sha256=native['source_sha256'],native_intake_sha256=hashlib.sha256(src.read_bytes()).hexdigest(),camera=cam,origin=origin.tolist(),image_sha256=hashlib.sha256((run/'images/day-reference.png').read_bytes()).hexdigest(),hits=results)
p=R/'captures/rightcoast33-main-view-localization.json';assert not p.exists();p.write_text(json.dumps(out,indent=2),encoding='utf-8');print(json.dumps([{'pixel':p['pixel'],'hit':None if not p['nearest_headland_hit'] else {k:p['nearest_headland_hit'][k] for k in ['object','location_blender','normal_blender']}} for p in results],indent=2))
