from pathlib import Path
R=Path(__file__).resolve().parents[1]
s=(R/'blender/model_lantern_island_29d.py').read_text().replace('29d','29e').replace('lantern_island_study_29b','lantern_island_study_29d')
s=s.replace("for i,p in enumerate(plan['terrain_vertices']):terrain.data.vertices[i].co=p","for i,p in enumerate(plan['terrain_vertices']):terrain.data.vertices[i].co=p\nfor i,p in enumerate(plan['path_vertices']):path.data.vertices[i].co=p")
s=s.replace("if max(p.vertices)>=n or p.index in protected:continue","if p.index in protected:continue\n if max(p.vertices)>=n:p.material_index=3;continue")
s=s.replace("close=min(((x-cx)/sx)**2+((y-cy)/sy)**2 for cx,cy,sx,sy,h in plan['knuckles'])","close=1.")
s=s.replace("if p.normal.z>.82 and p.center.z>10 and close>.45","if p.normal.z>.85 and p.center.z>11")
s=s.replace("assert sig(path)==old['path']","assert sig(path)['polygons']==old['path']['polygons']\nassert all(list(v.co)[:2]==co[:2] for v,co in zip(path.data.vertices,old['path']['vertices']))")
s=s.replace("'old_high_steep_faces':len(plan['old_selected_steep_faces']),'new_high_steep_faces':len(plan['new_selected_steep_faces']),","'path_max_slope_degrees':plan['path_max_slope_degrees'],")
s=s.replace('29b protected support retained','occupied-site support retained; road rebuilt over broad graded shoulder')
p=R/'blender/model_lantern_island_29e.py';assert not p.exists();p.write_text(s)
s=(R/'captures/check_island_29d.py').read_text().replace('29d','29e').replace('lantern_island_study_29b','lantern_island_study_29d')
s=s.replace("assert old[path]==new[path]","assert old[path]['polygons']==new[path]['polygons']\nassert all(a[:2]==b[:2] for a,b in zip(old[path]['vertices'],new[path]['vertices']))")
s=s.replace("'path_unchanged':True","'path_xy_topology_preserved_and_height_rebuilt':True")
p=R/'captures/check_island_29e.py';assert not p.exists();p.write_text(s)
s=(R/'tools/render_lantern_island_29d.py').read_text().replace('29d','29e')
s=s.replace('retaining actual protected20l path/pad/tree support','retaining occupied20l pad/tree support and rebuilding terrain-fitted road on broad graded shoulders')
s=s.replace('Native29e preserves paths and protected support triangles while remodeling peripheral terrain','Native29e rebuilds road heights and retains occupied building/tree support while remodeling connected terrain')
p=R/'tools/render_lantern_island_29e.py';assert not p.exists();p.write_text(s)
