"""Read-only preparation replay; --write-check writes only this preparation report.
Never launches an engine or creates an admission. Candidate reconstruction is
pure and compared byte-for-byte to the frozen finite input.
"""
import sys,os,time,json,platform,importlib.util
os.environ['OPENBLAS_NUM_THREADS']='1';sys.dont_write_bytecode=True
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent))
import geometry58l as g
import prepare_candidate58l as prep
import native_support58l as support

def check():
    start=time.monotonic();b=g.read(g.BINDING_PATH);c=g.read(g.CANDIDATE_PATH);proof=g.validate_candidate(c)
    changed=[]
    for row in b['files']:
        p=g.ROOT/row['path']
        if not p.is_file() or p.stat().st_size!=row['bytes'] or g.sha(p)!=row['sha256']:changed.append(row['path'])
    g.require(not changed,'ORIGINAL_INPUT_CHANGED:'+str(changed))
    rebuilt,_,_=prep.make();g.require(support.json_bytes(rebuilt)==g.CANDIDATE_PATH.read_bytes(),'DETERMINISTIC_CANDIDATE_BYTE_IDENTITY')
    for p in g.HERE.glob('*.py'):compile(p.read_bytes(),str(p),'exec')
    native_artifacts=[p.name for p in g.HERE.iterdir() if p.suffix=='.blend' or p.name in ('source-attempt.json','source-terminal.json','views-attempt.json','views-terminal.json')]
    g.require(not native_artifacts,'PREPARATION_ONLY_NO_NATIVE_OUTPUT_EXPECTED')
    for name,count in [('tests-geometry-normal.log',21),('tests-geometry-optimized.log',21),('tests-native-normal.log',31),('tests-native-optimized.log',31)]:
        s=(g.HERE/name).read_text();g.require('Ran '+str(count)+' tests' in s and s.rstrip().endswith('OK'),'PURE_TEST_REPORT:'+name)
    import numpy,scipy
    return dict(version=g.VERSION,passed=True,preparation_only=True,native_executed=False,source_saved=False,source_fresh_open=False,images_created=0,contact_acceptance=False,world_acceptance=False,global_GOAL=False,geometry=proof,deterministic_candidate_bytes=True,candidate_sha256=g.sha(g.CANDIDATE_PATH),candidate_bytes=g.CANDIDATE_PATH.stat().st_size,old_input_count=len(b['files']),old_input_bytes=sum(x['bytes'] for x in b['files']),all_old_input_bytes_unchanged=True,pure_tests=dict(geometry_normal=21,geometry_optimized=21,native_static_and_pure_normal=31,native_static_and_pure_optimized=31),python=platform.python_version(),numpy=numpy.__version__,scipy=scipy.__version__,pure_runtime_note='Scipy only prepares/audits finite candidate; native runtime needs Blender bundled NumPy, which is bound by full Blender executable SHA. No installation.',blender_executable_sha256=g.BLENDER_SHA,blender_file_sha_verified=g.sha(g.BLENDER)==g.BLENDER_SHA,total_seconds=time.monotonic()-start,permission_event=dict(action='write this package README/.gitignore and remove own generated bytecode cache',initial_outcome='authorization rejected before execution',same_call_evidence_retry_count=1,retry_outcome='succeeded',alternate_route_used=False))
if __name__=='__main__':
    import argparse
    ap=argparse.ArgumentParser();ap.add_argument('--write-check',action='store_true');args=ap.parse_args();r=check()
    if args.write_check:g.write(g.HERE/'PREPARATION_CHECK.json',r)
    print(json.dumps(r,indent=2))
