from pathlib import Path
import json,hashlib,math
R=Path(__file__).resolve().parents[1]
RUN=R/'captures/validation_runs/highcoast-reopen36g-20260909T023100Z-805ece112b8a42bcb3639d99f9e39ad6'
N=R/'captures/candidate_highcoast36c'
def read(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
m=read(RUN/'manifest.json');data=read(RUN/'images/candidate-reopen.json')
target=R/'reviews/36c-candidate-native-independent.json';report=read(target)
bindings=[dict(path=p,sha_matches=sha(RUN/p)==v['sha256'],size_matches=(RUN/p).stat().st_size==v['bytes']) for p,v in m['artifacts'].items()]
identity=[dict(file=p,candidate_same_as_frozen=sha(N/p)==sha(RUN/p)) for p in ['World36c.tscn','Game36c.tscn','candidate_game_36c.gd','repair-report.json']]
old=read(R/'reviews/36b-highcoast-independent-technical.json');triangles={r['name']:r['collision_triangles'] for r in old['tile_checks']}
removed=[dict(name=x['node'].split('/')[-1],indices=[int(v['index']) for v in x['removed_from_temporary_copy']]) for x in data['retained_harbor_path_removals']]
previous=[dict(name=x['name'],indices=x['removed_indices']) for x in report['known_removed_instances']]
distance=math.dist(data['flight_start'],data['flight_end'])
checks=dict(manifest_passed=m['status']=='passed' and m['passed'],all_bound_artifacts_same=all(x['sha_matches'] and x['size_matches'] for x in bindings),candidate_sources_same=all(x['candidate_same_as_frozen'] for x in identity),actual_invoked_script_matches_frozen=sha(R/'tools/check_highcoast_candidate_36g.gd')==sha(RUN/'check.gd'),exit0=len(m['stages'])==1 and m['stages'][0]['exit_code']==0,error_log_empty=(RUN/'native-candidate-reopen-error.log').stat().st_size==0,actual14tile_counts_match_saved_collision=len(data['tile_checks'])==14 and all(x['standard_paths'] and triangles[x['name']]==x['triangles'] for x in data['tile_checks']),final_count_matches_independent_savedWorld=data['scatter_total']==data['expected_scatter_total']==report['complete_saved_candidate_total']==54797,three_removals_match_prior_resource_delta=removed==previous,newpine_count_matches=data['new_pine_groups']==len(report['new_pine_helpers'])==22,ready_and_unowned_temporary_body_assertions=data['world_ready'] and data['world_processing_before_test_freeze'] and data['persistent_root_scatter_bodies']==0,selected_helper_is_known_pine=data['scatter_read_apply_no_change_checked'] in [x['name'] for x in report['new_pine_helpers']],flight_displacement_consistent=abs(distance-data['flight_distance_m'])<.0001 and distance>10,len8_frame30_samples=len(data['flight_samples'])==8 and [x['frame'] for x in data['flight_samples']]==list(range(0,240,30)))
result=dict(run=RUN.name,bindings=bindings,source_identity=identity,checks=checks,actual_report=data,flight_endpoint_displacement_recomputed_m=distance,all_reported_flight_positions_south_of_edited_terrain_domain=all(x['position'][2]>-2150 for x in data['flight_samples']),execution_scope=['Fresh World author instance outside tree verifies208tiles,14 exact mesh.get_faces()==shape.get_faces(),0 direct rootStaticBody,allgroves.owner==author,script and model_scene present.','Fresh Game root.add_child invokes normal_ready; asserts processing/chunks>=208/layout.props54797, then freezes World._process for bounded test.','One pine read_selected/apply_selected uses unchanged transform; resulting MultiMesh is distinct and selected transform identical. No editorGUI/extract/save-reload cycle.','240physics frames use existing game test_override_input;88.955m is endpoint displacement, not integrated traveled length.8 samples are30frame spaced, last recorded210;finish240 stored separately.','Sampled flight lies south of highcoast edit domain (Z>-2150), so it tests existing controller startup near harbor, not36b65point highcoast route or new-terrain corridor.'],limits=['Driver invokes workspace check and candidate paths, not frozen copies; current source-to-frozen SHA equality independently checked. No claim of immutable runtime dependency closure beyond bound files and inherited36b sources.','World processing deliberately frozen after normal_ready, so no full streaming/background generation endurance claim.','No fullfoot/corridor, actual editor button extraction/resave, allroute or visual acceptance.'],bounded_fresh_reload_pass=all(checks.values()))
report['fresh_reopen36g']=result
report['native_fresh_reload_proven']=result['bounded_fresh_reload_pass']
report['limits']=['Actual instantiated grove owner/helpers and one no-change read/apply now verified by36g script assertions; full editor GUI extraction/resave remains unverified.','54797 is complete savedWorld after3 harbor-road removals;54800 only applies to preceding highcoast adapter stage.','36g short controller movement is outside highcoast edited rectangle, not its full65point route; no fullfoot or lateral corridor claim.','Prior36b failedrun remains failed;36g is a separate successful bounded reload.']
target.write_text(json.dumps(report,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
print(json.dumps(dict(checks=checks,bindings=len(bindings),native_fresh_reload_proven=report['native_fresh_reload_proven'],displacement=distance),ensure_ascii=False))
