from pathlib import Path
import json,hashlib,numpy as np
from shapely.geometry import Polygon,Point
from shapely.ops import unary_union
R=Path(__file__).resolve().parents[1];p=R/'reviews/round-31d-rear-flank-independent.json';r=json.loads(p.read_text());gp=R/'captures/lantern_island_study_31d/geometry-evidence.json';e=json.loads(gp.read_text());ob=e['new']['island_c grass and exposed rock terrain'];v=np.array(ob['vertices']);faces=ob['polygons'];path=e['new']['island_c terrain fitted keeper paths'];pv=np.array(path['vertices']);road=unary_union([Polygon(pv[f][:,:2]) for f in path['polygons'] if np.cross(pv[f][1]-pv[f][0],pv[f][2]-pv[f][0])[2]>1e-9]);pads=unary_union([Polygon(s['polygon']) for s in e['sites']]);axes=r['actual_C_D_tree_local_axes'];trees=unary_union([Point(x).buffer(2) for x in axes]);masks={'road':road,'pads':pads,'current_tree_disks':trees};vertices=[]
for item in r['bounded_sample_vertex_adjacency']:
 vi=item['source_vertex'];incident=[fi for fi,f in enumerate(faces) if vi in f];region=unary_union([Polygon(v[faces[fi]][:,:2]) for fi in incident]);occupied=item['upward_adjacent_faces_intersecting_protection'];affected=[]
 for axis in axes:
  disk=Point(axis).buffer(2)
  if any(Polygon(v[faces[a['face']]][:,:2]).intersection(disk).area>1e-6 for a in occupied):
   if not any(np.linalg.norm(np.array(x)-axis)<.001 for x in affected):affected.append(axis)
 vertices.append({'source_vertex':vi,'actual_xyz':v[vi].tolist(),'sample_faces_using_vertex':[s['source_face'] for s in r['samples'] if vi in s['source_vertex_indices']],'incident_faces':incident,'upward_occupied_incident_faces':occupied,'substantive_current_tree_support_affected':len(affected)>0,'affected_local_tree_axes_xy_m_merged_within1mm':affected,'all_incident_face_projection_distance_m':{n:region.distance(m) for n,m in masks.items()},'edit_scope':'Requires current tree support preservation by boundary subdivision or explicit tree re-grounding; do not move whole shared vertex silently.' if affected else 'No occupied upward one-ring faces measured. Candidate for bounded local remesh, not unrestricted displacement; retain neighboring manifold edges and test actual candidate.'})
surface=[]
for s in r['samples']:
 ids=s['source_vertex_indices'];t=v[ids];lengths=[np.linalg.norm(t[(i+1)%3]-t[i]) for i in range(3)];i=int(np.argmax(lengths));surface.append({'source_face':s['source_face'],'actual_vertex_indices':ids,'actual_vertices_xyz':t.tolist(),'longest_edge':{'source_indices':[ids[i],ids[(i+1)%3]],'length_m':float(lengths[i]),'on_old_edge_midpoint_xyz':((t[i]+t[(i+1)%3])/2).tolist()},'on_old_face_centroid_xyz':t.mean(axis=0).tolist(),'split_scope':'Midpoint/centroid are exact positions on existing source geometry, only seed locations for sparse edge/face splits. They are not proposed final moved geometry or a visual solution. Split both adjacent faces of a shared edge to avoid T-junctions.'})
actions=['先以1038、1467两原长坡与1973/2181新增体面为同一接续问题；面39受树支承一环影响更强，可先留共享点408并在外部坡面边/面内新增少量点。','1467高端435同样牵动树盘，不应因只一角相关就冻结整坡。切分实际树盘边界交区，保存其线性支承小片，再释放面内远离占用的区；或记录对应树的重贴/移位。','1507是近竖壁，XY面积近零但3D面积8.035m²；应在3D边/面上切分，不依赖XY地形高度场表示。','将长边中点或面内点用作有限的拓扑控制，形成两到三段错高/错向宽面；新折线应止于局部肩宽内，避免从塔脚沿同一直线延伸到海侧。','给1973与旧坡统一安排接续边界，消除完整独立塞条轮廓；不要用更多凸包覆盖旧缝。当前此处所有采样顶点的一环都无实质占用，可优先局部原壳重排。','表中的一环投影距离只是局部占用诊断，不能直接当许可移动半径。任何改动都需检验新面反折、自交、闭合与真实支承；本报告不重跑这些全检查。']
report={'round':'31e','scope':'Bounded native31d topology intake for six directly localized rear faces. Reuses measured occupied one-ring evidence and computes coordinates/long edges/split seeds only. No31e actual candidate acceptance.','inputs':{str(q.relative_to(R)):hashlib.sha256(q.read_bytes()).hexdigest() for q in [p,gp]},'vertices':vertices,'faces':surface,'design_actions':actions,'full_reference_accepted':False,'candidate_geometry_pending':True,'limits':['Tree disks are current verification envelopes, not immutable user constraints.','Pad micro-sliver at face1260 is1.40e-7m2; not treated as substantive whole-face occupancy.','No Blender/GPU/full-support rerun.','All source indices apply to31d only; remesh renumbers vertices.']}
(R/'reviews/round-31e-topology-intake.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
md='# 31e 原壳拓扑与占用有界设计审查\n\n六个候选面都未直接进入当前占用区；真正需要处理的一环树支承点是408和435。其他列出的点没有实测占用向上邻面，可作为局部重排候选，不代表可以无限移动。\n\n|31d点|实际Blender XYZ，m|候选面|占用关联|\n|---:|---|---|---|\n'
for a in vertices:md+='|'+str(a['source_vertex'])+'|'+', '.join(f'{x:.6f}' for x in a['actual_xyz'])+'|'+','.join(map(str,a['sample_faces_using_vertex']))+'|'+('牵动树支承：'+str(a['affected_local_tree_axes_xy_m_merged_within1mm']) if a['substantive_current_tree_support_affected'] else '无实测占用向上邻面')+'|\n'
md+='\n408邻面24/25/26分别进入树盘2.533776/5.486331/2.159220m²；435邻面1107/1108分别进入0.460161/0.008055m²。435邻面1260与pad仅有1.40e-7m²微小边界碎片，不能据此冻结整面。\n\n## 稀疏切分的原面定位\n\n|面|最长边点号|长度m|原边中点XYZ（未移位）|\n|---:|---|---:|---|\n'
for a in surface:
 b=a['longest_edge'];md+='|'+str(a['source_face'])+'|'+str(b['source_indices'])+'|'+f"{b['length_m']:.4f}"+'|'+', '.join(f'{x:.5f}' for x in b['on_old_edge_midpoint_xyz'])+'|\n'
md+='\n这些中点和JSON中的面心只提供原几何上的切分起点，不是最终形态。共享边切分必须同时更新两侧面，避免T形接缝。\n\n'+'\n\n'.join('- '+a for a in actions)+'\n\n当前树盘不是用户永久硬约束。未运行Blender、GPU或完整支承验证；31e实际候选仍待核验。\n'
(R/'reviews/round-31e-topology-intake.md').write_text(md,encoding='utf-8');print(json.dumps({'vertices':len(vertices),'constrained_vertices':[a for a in vertices if a['substantive_current_tree_support_affected']],'faces':surface},ensure_ascii=False,indent=2))
