from pathlib import Path
exec(compile((Path(__file__).parent/'round-29a-independent-geometry.py').read_text().split('old=glb(OLD);')[0],'decoder','exec'))
helper=(R/'reviews/round-30d-cutback-intake.py').read_text(encoding='utf-8');exec(helper[helper.index('def triangles'):helper.index('road=unary_union')]);helper=(R/'reviews/round-30j-plan-independent.py').read_text(encoding='utf-8');exec(helper[helper.index('def overlay'):helper.index('rock_roofs=')]);exec((R/'reviews/round-32b-asset-footprint-decoder.py').read_text(encoding='utf-8'))
P=R/'captures/foreground_island_study_32d';d=glb(P/'island_a.glb');plan=json.loads((P/'design-plan.json').read_text());reopen=json.loads((R/'reviews/round-32d-reopened-source.json').read_text());pine=R/'assets/models/pine.glb';pt=asset_world_triangles(pine);zmin=float(pt[:,:,2].min());bottom=unary_union([Polygon(t[:,:2]) for t in pt if np.max(abs(t[:,2]-zmin))<1e-6 and Polygon(t[:,:2]).area>1e-10]);assert bottom.geom_type=='Polygon';base=np.array(bottom.exterior.coords);roofs=[]
for name,ts in d.items():
 for i,t in enumerate(ts):
  if np.cross(t[1]-t[0],t[2]-t[0])[2]>1e-9:roofs.append((name,i,t))
checks=[]
for tree,hit in zip(plan['trees_blender_xy_scale'],reopen['planned_trees_actual_rays']):
 x,y,scale=tree;mask=Polygon(base*scale+np.array([x,y]));cells=[]
 for name,fi,t in roofs:
  patch=Polygon(t[:,:2]).intersection(mask)
  if patch.area>1e-12:cells=overlay(cells,patch,plane(t),name+':'+str(fi),maximum=True)
 cover=unary_union([p for p,c,l in cells]);values=[float(np.dot(c,[*q,1])) for p,c,l in cells for q in points_any(p)];jumps=[]
 for i,(p,co,label) in enumerate(cells):
  for pp,cc,ll in cells[i+1:]:
   shared=p.boundary.intersection(pp.boundary)
   if shared.length>1e-8:jumps.extend(abs(float(np.dot(co-cc,[*q,1]))) for q in points_any(shared))
 center=[{'source':l,'height_m':float(np.dot(c,[x,y,1])),'normal':(-np.r_[c[:2],-1]/np.linalg.norm(np.r_[c[:2],1])).tolist()} for p,c,l in cells if p.buffer(1e-8).covers(Point(x,y))];row={'xy':[x,y],'scale':scale,'actual_base_polygon_xy':list(mask.exterior.coords),'actual_base_area_m2':mask.area,'unsupported_area_m2':mask.difference(cover).area,'highest_surface_height_min_max_m':[min(values),max(values)],'surface_height_range_m':max(values)-min(values),'max_internal_height_jump_m':max(jumps,default=0),'highest_surface_sources':sorted(set(l.split(':')[0] for p,c,l in cells)),'any_footpath_highest_surface_area_m2':unary_union([p for p,c,l in cells if 'paths' in l]).area,'axis_actual_GLB_sources':center,'native_reopen_axis_hit':hit['highest'],'actual_base_support_pass':mask.difference(cover).area<1e-8 and max(jumps,default=0)<1e-4,'base_is_flat_within0_1mm':max(values)-min(values)<1e-4};checks.append(row)
r={'round':'32d','scope':'Actual pine lowest-Z hexagonal bottom after glTF transforms, uniform authoredscale/noextra yaw, full clipped highest surface over all11actualGLB meshes for each of8planned trees. Reuses one independent saved-source reopen; not another Blender run.','pine_asset_sha256':sha(pine),'actual_pine_bottom_z_m':zmin,'actual_pine_bottom_polygon_xy':list(bottom.exterior.coords),'tree_count':len(checks),'checks':checks,'all_full_tree_bases_continuously_supported':all(x['actual_base_support_pass'] for x in checks),'all_full_tree_bases_flat_within0_1mm':all(x['base_is_flat_within0_1mm'] for x in checks),'no_tree_base_highest_path_hit':all(x['any_footpath_highest_surface_area_m2']<1e-10 for x in checks),'limits':['Authored native local tree placements; runtime transform/collision/visual confirmation still pending.','No tree canopy/branch or wholewalking collision check.','This complete base result replaces axis-only inference; source ray logs remain separate evidence.']}
(R/'reviews/round-32d-actual-tree-bases.json').write_text(json.dumps(r,indent=2),encoding='utf-8');p=R/'reviews/round-32d-foreground-independent-geometry.json';g=json.loads(p.read_text());g['actual_tree_base_report']='reviews/round-32d-actual-tree-bases.json';g['all8_actual_tree_bases_supported']=r['all_full_tree_bases_continuously_supported'];g['all8_actual_tree_bases_flat']=r['all_full_tree_bases_flat_within0_1mm'];g['pass']=g['pass'] and r['all_full_tree_bases_continuously_supported'];p.write_text(json.dumps(g,indent=2),encoding='utf-8');print(json.dumps({'support':r['all_full_tree_bases_continuously_supported'],'flat':r['all_full_tree_bases_flat_within0_1mm'],'not_on_path':r['no_tree_base_highest_path_hit'],'trees':[{'xy':a['xy'],'scale':a['scale'],'area':a['actual_base_area_m2'],'range':a['surface_height_range_m'],'missing':a['unsupported_area_m2'],'jump':a['max_internal_height_jump_m']} for a in checks]},indent=2))
