from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[1];run='lantern-island-31g-20260908T212230Z-081a9564b1f84eafb0afb166713c6b17';folder=R/'captures/validation_runs'/run/'images'
obs={
'night-reference':'中央岛比例与守塔屋在右保持。新后坡在全景左侧形成较连续暗绿区，前侧岩面仍密集，夜图不能用暗色遮蔽替代近图形体判断。',
'day-reference':'新后坡的草绿色大片在中央岛左侧已能辨认，岛体内部原来的岩坡层次变少。建筑尺度与全景构图维持，但新增绿色罩坡不符合参考中以短宽岩体为主的岛身。',
'day-d-front':'主要正面维持31f：上部大灰坡、两块相对孤立的凸石、局部直暗接缝仍在。背部真实重拓扑没有解决正面，不能连带提高这一面验收状态。',
'day-d-back':'对照31f有明确改变：塔脚向海口的中央亮窄条和长暗缝已不再连续出现，旧槽不再主导背面。但新区域读成从塔脚铺向海边的一大片绿色罩坡，缺少短宽错高的岩肩转折，仍有大板面感；低根轮廓更内收，几块保留旧岩的视觉分离感增大。没有30h那种密集细折扇。绿色覆盖与材质错误有关，不能据此断言换回岩色后形体必然合格。',
'day-c-front':'旧前肩仍像附在主坡上的两个独立凸石，邻接大斜板和尖暗缝保持。新后坡只在边缘有限露出，本图不支持宣称正面已达到参考。'
}
actions=[
'保留真实删除旧纵向内部边链并跨缝重接的方向，不恢复31f中央窄条。',
'先纠正84新面全部material_index=0的问题：根据实际面位置和坡面结构恢复岩体、湿岩根和有限草顶的材质分配。当前绿罩坡不能作为稳定形体评价底稿，但纠正颜色也不等于形体完成。',
'在恢复正确材质后，继续检查并组织中层短宽凸肩与下层钝根：使中层一侧抬出短的斜向承重面，另一侧在不同高度转折，折线在局部宽度内结束。不要只是把整个大绿板改灰，也不要再沿塔脚到海口做贯通窄槽。',
'低根与保留旧岩的可见关系需按实际镜头和局部截面复核。本图低根内收后旧岩更独立；若需要更宽承接，优先改主壳局部端部与肩根，不能统一把17岩外移或用相交面积冒充可见融合。',
'前部两孤立凸石及其后方大灰坡保留为独立待改项，不以背槽去除替代正面完成。'
]
def ev(p):return {'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
g=json.loads((R/'reviews/round-31g-independent-geometry.json').read_text());rt=json.loads((R/'reviews/round-31g-runtime-incremental.json').read_text());e=json.loads((R/'captures/lantern_island_study_31g/geometry-evidence.json').read_text());m=e['new']['island_c grass and exposed rock terrain']['materials'];assert len(m)==2220 and set(m[-84:])=={0}
r={'round':'31g','run_id':run,'visual_verdict':'retain_actual_cross_seam_retopology_but_reject_monolithic_green_rear_slope_correct_materials_then_assess_authored_short_shoulders','candidate_retained_for_iteration':True,'visual_complete':False,'full_reference_accepted':False,'all_reference_goal_complete':False,'reference':{**ev(R/'ref/1342.png'),'directly_viewed':True},'comparison_images':[{**ev(R/'captures/validation_runs/lantern-island-31f-20260908T204147Z-c8f8aed2cd5f43a7be28d18f0f9ba891/images/day-d-back.png'),'directly_viewed':True}],'images':[{'view':n,**ev(folder/(n+'.png')),'directly_viewed':True,'judgment':s} for n,s in obs.items()],'retained_changes':['Central narrow strip and long rear seam visible in31f no longer dominate31g back.','Cross-seam continuous main shell replaces the former filler-like strip.'],'remaining':['large continuous green rear slab or draped-slope reading','insufficient visible short staggered shoulder breaks','low root inset and increased visual separation from several old rocks','unchanged front isolated boulders and broad planes'],'material_defect':{'actual_native_last84_replacement_face_material_indices':[0],'builder_source':ev(R/'captures/lantern_island_study_31g/builder.py'),'actual_native_geometry':ev(R/'captures/lantern_island_study_31g/geometry-evidence.json'),'image_confirmation':'Entire replacement rear slope reads green in day-d-back and day-reference.','material_fix_is_not_geometry_acceptance':True},'next_actions':actions,'geometry':{'report':ev(R/'reviews/round-31g-independent-geometry.json'),'passed':g['pass'],'actual_triangles':2220,'actual_vertices':1112,'removed_cut_faces':448,'removed_old_internal_edges':637,'boundary_edges_retained':70,'new_replacement_triangles':84,'changed_or_new_triangles_vs31f':324,'actual_local_AABB_pairs':3322,'illegal_intersections_found_at_stated_tolerance':0,'actual14trunk_footprints_continuously_supported':True},'root_runtime_report_read':{'report':ev(R/'reviews/round-31g-runtime-incremental.json'),'passed':rt['passed'],'bindings':rt['binding_count'],'placements_per_view':59,'maximum_position_delta_m':max(v['maximum_position_delta_m'] for v in rt['views']),'maximum_footing_delta_m':max(v['maximum_footing_delta_m'] for v in rt['views'])},'limits':['Allfive original31g PNGs directly viewed; no Blender/GPU or geometry suite rerun during this visual review.','Native topology validity does not imply art acceptance.','Green material defect is directly corroborated by84 actual material indices; flat appearance cannot be attributed solely to material without a corrected same-geometry view.','Visual separation from old rocks is not a measured whole-contact loss or floating-object assertion.','Actual flat trunk base continuous support does not prove everywhere flat-bottom contact.','Historical dense-fan rejected candidate was30h; upcoming31h is a separate31g material revision.','No fullwalking or20reference goal completion.']}
(R/'reviews/round-31g-island-independent-review.json').write_text(json.dumps(r,ensure_ascii=False,indent=2),encoding='utf-8')
md='# 31g 岛体独立造型审查\n\n保留真正跨缝重拓扑的方向，整体不接受。31f中央窄条和贯穿海口的长缝在背图中确实消失，但新区域变成大块绿色罩坡，短宽岩肩层次仍不足。当前84新面全部使用material_index=0，是明确的材质错误；修正材质后还须重新判断形体，不能把绿色大板变灰等同完成。\n\n已直接逐张查看五张31g原图、31f背图与1342。运行：`'+run+'`。\n\n'
for n,s in obs.items():md+='## '+n+'\n\n'+s+'\n\n'
md+='## 后续有界方向\n\n'+'\n\n'.join('- '+a for a in actions)+'\n\n## 已通过证据与验收边界\n\n实际GLB为2220三角、1112点的有向闭合单壳。448选面与637旧内部边确实删除，70边界边保持，84新面真实存在。324改变/新切分三角对整壳3322对候选未发现共享特征0.1mm容差外自交；道路、pad及14棵真实干底支承通过。旧2m盘不冻结，连续支承也不代表平底与坡面处处贴合。\n\n读到本版运行审计：'+str(rt['binding_count'])+'绑定、每视角59落点，最大位置差'+str(r['root_runtime_report_read']['maximum_position_delta_m'])+'m，基础样本最大差'+str(r['root_runtime_report_read']['maximum_footing_delta_m'])+'m。拓扑删除和运行门禁通过不代表美术通过。低根与旧岩视觉分离仅是本图判断，不冒充全接触丢失的测量。\n\n历史密集折扇失败版本为30h；接下来31h是从本版修正材质的新候选，两者不可混淆。`full_reference_accepted=false`，全部20参考目标仍未完成。\n'
(R/'reviews/round-31g-island-independent-review.md').write_text(md,encoding='utf-8');print(json.dumps({'written':True,'runtime':r['root_runtime_report_read'],'full_reference_accepted':False},indent=2))
