from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[1];run='lantern-island-31h-20260908T212800Z-78b153beccc94a60ba27ba0e79a1cfaa';folder=R/'captures/validation_runs'/run/'images';plan=json.loads((R/'captures/lantern_island_study_31h/reform-plan.json').read_text());rt=json.loads((R/'reviews/round-31h-runtime-incremental.json').read_text())
obs={
'night-reference':'中央岛保持较合适的建筑/陆体比例与右侧守塔屋。31g后部大片绿区恢复为岩色，但夜景全图无法证明中层短肩成立，当前灰岩整体仍较整齐。',
'day-reference':'中央岛后坡的绿色材料错误已消除，岩色与前部更一致。岛身后侧仍呈连续罩坡，缺少参考1342中错高、短宽的岩根关系；全景比例维持不代表形体完成。',
'day-d-front':'主要前面仍与31g/f相同，两凸肩像独立石块，上台大灰面和局部直暗缝保持。本轮只改材料，正面没有新的真实造型进展。',
'day-d-back':'与直接看过的31g同形体背图对照，绿板确实改成岩色，旧中央窄条和纵贯海口的长缝仍已消除。但大灰罩坡从上方直接铺到低根，面间转折太弱，中层缺少可辨认的短宽凸肩。上端保留草面形成尖三角碎片，像按三角阈值涂色。低处几块保留岩与内收主坡仍相对独立；没有30h密折扇，也未达到参考的自然块肩层次。',
'day-c-front':'正面孤立凸石及其后大斜面仍未改变。当前图不能用于接受背面以外的岩岛造型。'
}
actions=[
{'area':'中层短宽肩','actual_controls':['high cross shoulder','west broad flank','middle east return'],'proposal':'以high cross shoulder(-6.8,8.5,8.1)与west broad flank(-14,10,5.4)附近为一个连续面区，明确区分上短坡、中层斜肩顶和肩前短断面；用前后两条错向短边限定肩厚，必要时添加少量真实共边点。middle east return(-1,12,6.1)接其一端并在不同高度收束，不沿整个岛面拉成同一条横阶。不要只抬一个点做新尖峰或凸按钮。'},
{'area':'高坡到中肩','actual_controls':['high east fold','middle east return'],'proposal':'high east fold(1,9.5,8.2)与middle east return之间需要明确可见的短坡折和转向，肩顶前后坡向不同；避免用一组近共面的宽三角从塔基一直覆盖至下根。保留真实pad上方支承，先改其外部已有面区。'},
{'area':'低根钝端','actual_controls':['low west blunt root','east sea nose','outer rear shoulder','submerged rear base'],'proposal':'low west blunt root(-9,17,2.8)、east sea nose(2,20,1.4)、outer rear shoulder(-4,24,.65)作为不同方向的低根端部，分别形成短厚、非同高的断面并与上方肩前面连接，避免三点成为同一张长斜板的末端。submerged rear base(-6,20,-5.85)承担闭壳底部，可保持它与局部外根之间的连续底壳；不凭增加水下面积声称水上造型改善。'},
{'area':'草岩交界','actual_controls':['high cross shoulder','high east fold'],'proposal':'中肩真实坡折确定后，再沿肩后缘组织一片连贯的有限草顶，消除当前尖三角色片；不要把逐三角centroid/normal阈值当最终美术边界，也不继续仅换颜色迭代。'},
{'area':'保留与约束','actual_controls':[],'proposal':'保留去掉旧窄条/长缝的真实新拓扑和原生建筑尺度；继续保留实际道路/pad/树干支承，旧2m盘不冻结。前部两孤立凸石仍独立待改。上述坐标是当前控制点定位，不是未经验证的最终位移处方。'}
]
def ev(p):return {'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
report={'round':'31h','run_id':run,'visual_verdict':'material_defect_corrected_but_rear_monolithic_slope_needs_real_short_shoulder_and_blunt_root_breaks','candidate_retained_for_iteration':True,'visual_complete':False,'full_reference_accepted':False,'all_reference_goal_complete':False,'reference':{**ev(R/'ref/1342.png'),'directly_viewed_in_current_continuing_review':True},'comparison_images':[{**ev(R/'captures/validation_runs/lantern-island-31g-20260908T212230Z-081a9564b1f84eafb0afb166713c6b17/images/day-d-back.png'),'directly_viewed_in_current_continuing_review':True},{**ev(R/'captures/validation_runs/lantern-island-31f-20260908T204147Z-c8f8aed2cd5f43a7be28d18f0f9ba891/images/day-d-back.png'),'directly_viewed_in_current_continuing_review':True}],'images':[{'view':n,**ev(folder/(n+'.png')),'directly_viewed':True,'judgment':s} for n,s in obs.items()],'retained_changes':['Correct72 exposed replacement faces from grass to native rock material.','Preserve31g actual cross-seam topology and disappearance of former rear strip/long cleft.'],'remaining':['large grey draped-slope mass','weak midlevel convex shoulder break','pointed triangular grass patches','isolated front boulders','visually detached several low rocks versus inset main root'],'actual_eight_controls':plan['controls'],'next_bounded_reform':actions,'identity_evidence':{'report':ev(R/'reviews/round-31h-material-identity.json'),'19native_geometry_exact31g':True,'actual3624_GLB_triangle_counter_exact':True,'72rock_faces_and12grass_faces':True,'no_new_support_or_intersection_scan_needed':True},'root_runtime_report_read':{'report':ev(R/'reviews/round-31h-runtime-incremental.json'),'passed':rt['passed'],'bindings':rt['binding_count'],'positions_each_view':59,'maximum_position_delta_m':max(v['maximum_position_delta_m'] for v in rt['views']),'maximum_footing_delta_m':max(v['maximum_footing_delta_m'] for v in rt['views'])},'limits':['This is direct five-view visual review, no new native/GPU/support/self-intersection run.','Control names identify actual source coordinates, not proof of visual shoulder function.','Proposed width/edge organization is an art direction requiring actual candidate geometry and views, not a simulated guaranteed result.','Low-rock separation is visual, not newly measured lost contact or floating.','Continuous support is not full flat-trunk-bottom contact.','Reference1342 is a style/form reference, not an exact rear-side reconstruction.','Full20reference and walking goals remain unaccepted.']}
(R/'reviews/round-31h-island-independent-review.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
md='# 31h 岛体独立造型审查\n\n材质错误已修正，整体仍不接受。旧窄条和纵向长缝保持消除，但去掉绿色覆盖后，可以确认背部主要问题仍是大灰罩坡；中层没有明确短宽凸肩，草顶又出现尖三角色片。下一轮需要真实坡折与低根厚度，不能继续仅换颜色。\n\n本版五原图已直接逐张查看；对照持续审查中直接看过的31g、31f背图与1342。运行：`'+run+'`。\n\n'
for n,s in obs.items():md+='## '+n+'\n\n'+s+'\n\n'
md+='## 结合实际控制点的有界改形\n\n'
for a in actions:md+='- '+a['area']+'：'+a['proposal']+'\n\n'
md+='## 验证边界\n\n19个原生对象、全部3624实际GLB三角与31g精确相同，仅72面改石材、12上部面保留草。继承31g道路/pad/真实树干支承、闭合和局部离散相交证据，不重复全扫。读取本版运行审计：201绑定、每视角59落点；位置最大差'+str(report['root_runtime_report_read']['maximum_position_delta_m'])+'m，基础样本最大差'+str(report['root_runtime_report_read']['maximum_footing_delta_m'])+'m。\n\n这些证据不代表造型通过。实际控制点名称不等于已形成相应短肩；上述点位用于定位下一稿，并非未经验证的位移处方。`full_reference_accepted=false`，全部20参考目标仍未完成。\n'
(R/'reviews/round-31h-island-independent-review.md').write_text(md,encoding='utf-8');print(json.dumps({'written':True,'full_reference_accepted':False,'runtime':report['root_runtime_report_read']},indent=2))
