from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[1];run='lantern-island-31c-20260908T201128Z-28759710080745f9bea8113b6cf38f92';folder=R/'captures/validation_runs'/run/'images'
obs={
'night-reference':'中央岛的建筑原生尺度、守塔屋在右与较低树组保留。局部肩在夜间中景分辨度有限，不能从这张图判定背槽或短宽岩肩完成；1342中央岛仍有更自然的错位块面关系。',
'day-reference':'总体比例和岩群轮廓保留，前部形态有小幅变化，但远景不足以辨别槽内新体和两岸关系。应以实际近视图和局部截面为准。',
'day-d-front':'两前肩比31b短，方向差异增加，避免继续变成长斜板。但现在又偏向两块孤立凸石，左肩形成近圆多边轮廓，中央肩呈较小尖块；与后方大灰坡的组织仍生硬。没有恢复31a规则平顶柱，却也没有建立统一短宽承重层次。',
'day-d-back':'第三体可见为槽中一条偏细长的亮灰尖条。它遮挡部分旧黑槽，但两侧、尤其近塔侧仍有长缝，塔基下贯向海面的直切读法没有解决。不是已经接上两岸的短宽斜肩，必须返工。',
'day-c-front':'比31b的两张偏长同向斜面更短，左顶与中顶走向不再完全相同。但两凸块的独立轮廓感回升，左侧旧大斜板和上台宽灰面仍明显；单纯缩短凸包并没有把这些大面组织成参考式岩根。当前只保留缩短错向方向，不能宣布前部完成。'
}
def file(p):return {'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
g=json.loads((R/'reviews/round-31c-independent-geometry.json').read_text());d=json.loads((R/'reviews/round-31c-back-cleft-diagonal-check.json').read_text());rt=json.loads((R/'reviews/round-31c-runtime-incremental.json').read_text())
actions=['先修第三体靠塔低Y岸的真实空隙：在不动pad支承面的前提下让有限中段实体穿过该空隙，实际截面确认双侧进入。不得将已填的较远Y次级缝误作主目标通过。','即使双岸接上，仍要避免顶面成为纵向尖条或横板；让宽根、偏转前端和高低错位在D背图可读。不要把背槽整片填成一个平坡。','前两体暂保留缩短与错向的方向；下一步应将凸块后部与原宽坡的真实宽面组织一起修改，减少封闭独立石块轮廓感，不靠更多小块遮坡。','实际支承/闭合与美术结论分开：本版基础几何有效，但背槽双岸目标未通过，整体视觉仍失败。']
report={'round':'31c','run_id':run,'visual_verdict':'reject_rear_cleft_filler_unconnected_near_pad_bank_front_direction_partial_only','visual_complete':False,'full_reference_accepted':False,'all_reference_goal_complete':False,'reference':{**file(R/'ref/1342.png'),'directly_viewed_in_current_continuing_review':True},'comparison':{**file(R/'captures/validation_runs/lantern-island-31b-20260908T195540Z-dc0f57e0a037461484c11dba7dcb8b57/images/day-c-front.png'),'directly_viewed_in_current_continuing_review':True},'images':[{'view':n,**file(folder/(n+'.png')),'directly_viewed':True,'judgment':s} for n,s in obs.items()],'next_actions':actions,'geometry':{'report':'reviews/round-31c-independent-geometry.json','base_shell_and_support_pass':g['base_geometry_and_support_pass'],'requested_bilateral_back_cleft_pass':g['back_cleft_bilateral_connection_pass'],'combined_geometry_scope_pass':g['pass'],'main_triangles':2178,'path_17rocks_and_road_pad_current14tree_support_preserved':True,'diagonal_target_gap_m':d['gaps'][0]['actual_new_unfilled_gap_length_m'],'target_diagonal_z_m':5.137,'target_remaining_gap_xy':d['gaps'][0]['actual_unfilled_xy_geometry'],'secondary_farther_y_gap_closed':d['any_secondary_gap_connected'],'local_crosscut_report':'reviews/round-31c-back-cleft-local-crosscheck.json','diagonal_report':'reviews/round-31c-back-cleft-diagonal-check.json','interpretation':'Target near-pad primary gap remains1.24170075m on diagonal. Secondary farther-Y gap closure is real but does not satisfy primary two-bank connection. Full-width X gaps are not used as visible-cleft width.'},'root_runtime_report_read':{'path':'reviews/round-31c-runtime-incremental.json','passed':rt['passed'],'binding_count':rt['binding_count'],'placements_each_view':59,'maximum_position_delta_m':max(v['maximum_position_delta_m'] for v in rt['views']),'maximum_footing_delta_m':max(v['maximum_footing_delta_m'] for v in rt['views'])},'limits':['No Blender/GPU rerun.','All five original screenshots directly viewed.','No exterior-area art score, exact visible-crevice segmentation, or full-reference acceptance.','Runtime report read from root, not independently rerun.']}
(R/'reviews/round-31c-island-independent-review.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
md='# 31c 岛体独立造型审查\n\n31c整体不接受。两前肩缩短、错向，但独立小凸块感仍强；背槽第三体像塞入槽内的细长尖条，靠塔一侧长缝仍在。背槽不能标记解决。\n\n本次直接看五张原始图，对照持续审查中直接看过的1342和31b。运行：`'+run+'`。\n\n'
for n,s in obs.items():md+='## '+n+'\n\n'+s+'\n\n'
md+='## 实际几何与返工边界\n\n基础几何/支承通过：2178三角闭合单连通，17岩/path、完整道路/pad/当前14树盘支承保持。但完整本轮目标包含背槽双岸连接，此项失败，因此独立几何JSON将 base_geometry_and_support_pass=true、back_cleft_bilateral_connection_pass=false、pass=false 分开记录。\n\n与两个原像素壁点XY一致的斜向截线，在z5.137m实测靠塔主缝仍长1.241701m，端点约(-2.531009,4.982988)至(-2.602758,6.222614)。第三体在这一侧交叠为0。更远Y的一条次级缝确实闭合，但不是靠塔主目标。局部Y截线也有0.8745–2.6831m缺口；大范围X截线只作方向诊断，不当作画面槽宽。\n\n'
md+='\n'.join('- '+a for a in actions)+'\n\n已读取root runtime审计：199绑定、每视角59落点，最大位置差'+str(report['root_runtime_report_read']['maximum_position_delta_m'])+'m，基础样本最大差'+str(report['root_runtime_report_read']['maximum_footing_delta_m'])+'m。运行通过不能代替几何设计或视觉目标。未重跑Blender/GPU，不按新增面积评分，full_reference_accepted=false。\n'
(R/'reviews/round-31c-island-independent-review.md').write_text(md,encoding='utf-8');print('31c final MD/JSON written; base support true, target bilateral false, visual false.')
