from pathlib import Path
exec(compile((Path(__file__).parent/'round-29a-independent-geometry.py').read_text().split('old=glb(OLD);')[0],'actualGLB_decoder','exec'))
P=R/'captures/lantern_island_study_31e';e=json.loads((P/'geometry-evidence.json').read_text());plan=json.loads((P/'reform-plan.json').read_text());tn='island_c grass and exposed rock terrain';oldv=np.array(e['old'][tn]['vertices']);newv=np.array(e['new'][tn]['vertices']);actual=glb(P/'island_c.glb');key=next(k for k in actual if 'olive grass' in k);actual_points=np.concatenate(actual[key]);moves={pointkey(m['before']):m for m in plan['actual_moved_vertices']};rows=[]
for vi,kind in [(409,'old slope lower join'),(938,'old slope upper flank'),(941,'old slope rear flank'),(997,'old slope high flank'),(411,'historical rear union shoulder'),(428,'historical rear union high join'),(419,'historical rear union mid join'),(435,'tree support associated high anchor'),(408,'tree support associated outside anchor')]:
 before=oldv[vi];m=moves.get(pointkey(before));after=np.array(m['after']) if m else before;nearest=float(np.min(np.linalg.norm(actual_points-after,axis=1)));assert nearest<1e-5
 rows.append({'actual31d_vertex_index':vi,'role':kind,'actual_before_xyz':before.tolist(),'actual_after_xyz':after.tolist(),'actual_delta_xyz':(after-before).tolist(),'actual_displacement_m':float(np.linalg.norm(after-before)),'after_point_in_real31eGLB_distance_m':nearest,'matched_moved_record':m is not None})
assert all(x['actual_displacement_m']>1e-5 for x in rows if x['actual31d_vertex_index'] in [409,938,941,411,428,419]);assert all(x['actual_displacement_m']==0 for x in rows if x['actual31d_vertex_index'] in [435,408])
oldset={pointkey(v) for v in oldv};old_moved=sum(pointkey(m['before']) in oldset for m in plan['actual_moved_vertices']);result={'scope':'Named original31d source vertices matched by actualXYZ to recorded movement, each after position verified in real31eGLB; does not count newly bisected vertices as old source vertices.','anchors':rows,'total_moved_records':len(plan['actual_moved_vertices']),'moved_records_matching_original31d_vertices':old_moved,'moved_new_bisect_vertices':len(plan['actual_moved_vertices'])-old_moved,'pass':True}
(R/'reviews/round-31e-anchor-change-check.json').write_text(json.dumps(result,indent=2),encoding='utf-8');p=R/'reviews/round-31e-independent-geometry.json';r=json.loads(p.read_text());r['old_slope_and_existing_union_actual_anchor_changes']=result;r['scope']='Actual31d to31e original-slope and existing-union discrete reform. Required support, connected/closed main shell, finite normal change, changed-region triangle intersection sweep and named original anchor changes. Historical convex operands are construction history only.';p.write_text(json.dumps(r,indent=2),encoding='utf-8');print(json.dumps(result,indent=2))
