from pathlib import Path
src=(Path(__file__).parent/'round-31c-back-cleft-local-crosscheck.py').read_text(encoding='utf-8').split('\nrows=[]')[0];exec(compile(src,'actual_local_section_helpers','exec'))
loc=json.loads((R/'reviews/round-31b-back-cleft-localization.json').read_text());q=np.array(loc['samples'][2]['hit_blender_xyz'][:2]);p=np.array(loc['samples'][0]['hit_blender_xyz'][:2]);u=(p-q)/np.linalg.norm(p-q);start=q-u*2;end=p+u*2;line=LineString([start,end]);z=5.137
a,b,c=section(old[key],z),section(new[key],z),section(operand,z);oi=parameters(a.intersection(line),line);ni=parameters(b.intersection(line),line);ci=parameters(c.intersection(line),line);gaps=[]
for left,right in zip(oi,oi[1:]):
 if right[0]-left[1]<1e-5:continue
 gap=LineString([line.interpolate(left[1]),line.interpolate(right[0])]);ll=LineString([line.interpolate(left[0]),line.interpolate(left[1])]);rl=LineString([line.interpolate(right[0]),line.interpolate(right[1])]);lp=ll.intersection(c).length;rp=rl.intersection(c).length;unfilled=gap.difference(b)
 gaps.append({'old_gap_start_xy':list(gap.coords[0]),'old_gap_end_xy':list(gap.coords[-1]),'old_gap_length_m':gap.length,'actual_new_unfilled_gap_length_m':unfilled.length,'actual_unfilled_xy_geometry':unfilled.__geo_interface__,'operand_overlap_near_pad_bank_m':lp,'operand_overlap_far_bank_m':rp,'both_banks_connected':lp>.01 and rp>.01 and unfilled.length<1e-5})
assert len(gaps)>0
result={'scope':'One diagonal horizontal crosscut aligned between XY of the two independently verified upper rear-wall pixel hits; source heights replaced by common nonvertex z5.137m. ActualGLB sections, not inferred3D image gap. Target is the first gap from the near-pad bank; a secondary farther-Y gap is reported separately and cannot substitute for target closure.','z_m':z,'line_xy':[start.tolist(),end.tolist()],'old_intervals_along_line_m':oi,'new_intervals_along_line_m':ni,'operand_intervals_along_line_m':ci,'gaps':gaps,'target_gap_index':0,'both_banks_connected':gaps[0]['both_banks_connected'],'any_secondary_gap_connected':any(g['both_banks_connected'] for g in gaps[1:])}
(R/'reviews/round-31c-back-cleft-diagonal-check.json').write_text(json.dumps(result,indent=2),encoding='utf-8')
p=R/'reviews/round-31c-independent-geometry.json';r=json.loads(p.read_text());r['base_geometry_and_support_pass']=r.get('base_geometry_and_support_pass',r['pass']);r['back_cleft_bilateral_connection_pass']=result['both_banks_connected'];r['pass']=r['base_geometry_and_support_pass'] and r['back_cleft_bilateral_connection_pass'];r['verdict']='Base shell/support checks pass; requested bilateral rear-cleft connection is not achieved at tested local sections.';r['bounded_back_cleft_both_banks_check'].update({'local_Y_crosscuts_report':'reviews/round-31c-back-cleft-local-crosscheck.json','diagonal_crosscut_report':'reviews/round-31c-back-cleft-diagonal-check.json','local_bilateral_pass':False,'scope':'Actual local Y and diagonal section evidence supersedes any interpretation of full-X gap as the visible cleft. Low-Y near-pad bank remains unconnected at sampled mid-level crosscuts. No whole crevice segmentation.'});p.write_text(json.dumps(r,indent=2),encoding='utf-8')
print(json.dumps(result,indent=2))

