from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[1];run='lantern-island-31i-20260908T214100Z-02d75d5cf747426d88e00816dda55bd0';folder=R/'captures/validation_runs'/run/'images';g=json.loads((R/'reviews/round-31i-independent-geometry.json').read_text());bands=json.loads((R/'reviews/round-31i-shoulder-band-check.json').read_text());rt=json.loads((R/'reviews/round-31i-runtime-incremental.json').read_text())
obs={
'night-reference':'中央岛比例与右侧守塔屋保持，背部新折口在全景左侧可见些许较深暗面，但夜图不足以接受中层岩肩。',
'day-reference':'中央岛左侧的新暗折口比31h可辨认；这是本版真实改形的可见变化。但全景仍以大灰坡为主，整体尚未呈现参考1342中自然的短宽错位岩根。',
'day-d-front':'主要正面两孤立凸石、大灰坡与局部暗缝保持，背部两肩带改动没有解决这一面。',
'day-d-back':'相对31h出现真实肩前断面与新的明暗转折，靠海一处大暗三角口很明显，低根也有实际偏转；旧贯穿塔脚的窄条长缝没有回来。但上方大片灰坡仍近似一张罩面，新增肩更像其边缘被折出一个突檐/直切口，未形成自然短厚块肩。低处几块旧岩仍显独立，不能称低根分离已解决。尖三角草碎片已不见，没有30h密折扇。',
'day-c-front':'前面依然是两块相对独立的凸石及其后方大斜板；本次肩带不改变正面验收结论。'
}
actions=[
'保留本版共享边切分形成实际有限肩宽的做法和旧窄条去除；几何成立不能替代形体接受。',
'西肩1108/1104到新增1112/1113的实际顶面约24.83m²，两三角法线仅差1.136°。下一步要缩短其连续同坡向读法：将肩后接续与前缘一端错高、错向，形成一段更短的斜顶和侧断面；避免四点同步抬高推出整块板，也不只推一个点生成尖峰。',
'东肩前缘1114/1115的实际折角93.978°，明显比西肩28.104°更急。应对这个局部断面检查伸出量和下方承接：可以让前缘较低/更内收或下侧根部适度向外承接，使坡前是短厚斜断面，避免暗口像直立切墙或檐下洞。这里不是按角度阈值评分，仍以实际图为准。',
'低根1106/1107/1111虽已改动，图上几块原岩仍分离。需把肩前断面与一处钝根作为同一小区域组织；先确认希望连接的实际旧岩和可见方向，再调整主壳局部端部，不统一外移17岩、不用截面交叠面积声称视觉融合。',
'前部两孤立凸石与其后上台灰坡仍是独立待改项。不得因为背部出现新暗面就将正面或全部参考标记完成。'
]
def ev(p):return {'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
r={'round':'31i','run_id':run,'visual_verdict':'retain_actual_shared_edge_shelf_width_but_reject_large_cap_and_abrupt_front_cut_reading','candidate_retained_for_iteration':True,'visual_complete':False,'full_reference_accepted':False,'all_reference_goal_complete':False,'reference':{**ev(R/'ref/1342.png'),'directly_viewed_in_continuing_review':True},'comparison_images':[{**ev(R/'captures/validation_runs/lantern-island-31h-20260908T212800Z-78b153beccc94a60ba27ba0e79a1cfaa/images/day-d-back.png'),'directly_viewed_in_continuing_review':True}],'images':[{'view':n,**ev(folder/(n+'.png')),'directly_viewed':True,'judgment':s} for n,s in obs.items()],'retained_changes':['Actual finite-width shoulder caps and visible front breaks.','Old tower-to-sea narrow strip and cleft remain removed.','Triangular green patches removed.'],'remaining':['large upper grey cap','abrupt dark front cut or eave-like reading','low-root visual separation from several old rocks','unchanged isolated front shoulders'],'next_actions':actions,'actual_band_measurements':[{k:a[k] for k in ['band','front_edge_vertices','back_edge_vertices','front_edge_length3d_m','back_edge_length3d_m','front_to_back_minimum_XY_segment_distance_m','cap_surface_area_m2','cap_internal_dihedral_angle_deg','front_crease_normal_angle_deg']} for a in bands['bands']],'geometry':{'report':ev(R/'reviews/round-31i-independent-geometry.json'),'passed':g['pass'],'actual_main_triangles':2228,'actual_vertices':1116,'moved_source_controls':5,'new_shared_edge_points':4,'actual_changed_or_retriangulated_triangles':60,'local_AABB_pairs':1053,'illegal_intersections_found_at_stated_tolerance':0,'actual14_trunk_footprints_supported':True,'shared_edge_report':ev(R/'reviews/round-31i-shoulder-band-check.json')},'root_runtime_report_read':{'report':ev(R/'reviews/round-31i-runtime-incremental.json'),'passed':rt['passed'],'bindings':rt['binding_count'],'positions_each_view':59,'maximum_position_delta_m':max(v['maximum_position_delta_m'] for v in rt['views']),'maximum_footing_delta_m':max(v['maximum_footing_delta_m'] for v in rt['views'])},'limits':['Five31i originals directly viewed; no geometry/Blender/GPU rerun during visual review.','Band normal-angle measurements identify actual geometry, not universal art thresholds.','The visible dark opening has not been independently pixel-ray-mapped to a particular band; do not infer screen left/right from native west/east names.','Low-rock visual separation is not a new whole-contact or floating claim.','Shared source edge1108–1106 survives legally as a BEAUTY neighbor-quad diagonal; actual split segments each have2incident faces, not a T-junction.','Full20reference and fullwalking goals remain unaccepted.']}
(R/'reviews/round-31i-island-independent-review.json').write_text(json.dumps(r,ensure_ascii=False,indent=2),encoding='utf-8')
md='# 31i 岛体独立造型审查\n\n有限宽肩和前断面确实出现，整体仍不接受。与31h相比，背面有新的明暗折口和低根变化，但大灰罩坡仍主导；一处前断面又形成过强暗口/突檐感，尚不像参考的短厚错位块肩。低根与部分旧岩的分离感保持。\n\n本次直接逐张查看五张原图，对照持续审查中已直接看过的31h背图和1342。运行：`'+run+'`。\n\n'
for n,s in obs.items():md+='## '+n+'\n\n'+s+'\n\n'
md+='## 下一步有界改形\n\n'+'\n\n'.join('- '+a for a in actions)+'\n\n## 实际验证与限制\n\n西肩前/后缘5.788/7.596m、最小XY宽3.630m，顶面24.834m²，顶内折角1.136°，前折28.104°。东肩3.600/4.134m、宽2.280m，顶面9.928m²，顶内折角0.096°、前折93.978°。这些是实际BEAUTY三角测量，不是艺术分数。当前暗口未逐像素射线对应特定肩带，不能按west/east名字直接套屏幕左右。\n\n实际2228三角/1116点主壳闭合单连通，道路/pad/14真实干底支承与17岩/路径通过。60改变或新切分三角对整壳1053候选对无共享特征0.1mm容差外相交。共享切分点各边段有两邻面；旧1108–1106边作为BEAUTY邻面quad内对角线保留是合法的，不当作未切边/T缝。\n\n运行审计：'+str(rt['binding_count'])+'绑定、每视角59点，位置最大差'+str(r['root_runtime_report_read']['maximum_position_delta_m'])+'m，基础样本最大差'+str(r['root_runtime_report_read']['maximum_footing_delta_m'])+'m。以上不代表美术通过。`full_reference_accepted=false`，全部20参考目标仍未完成。\n';(R/'reviews/round-31i-island-independent-review.md').write_text(md,encoding='utf-8');print(json.dumps({'written':True,'runtime':r['root_runtime_report_read'],'full_reference_accepted':False},indent=2))
