from pathlib import Path
exec(compile((Path(__file__).parent/'round-29a-independent-geometry.py').read_text().split('old=glb(OLD);')[0],'decoder','exec'))
from shapely.geometry import shape
helper=(R/'reviews/round-30d-cutback-intake.py').read_text(encoding='utf-8');exec(helper[helper.index('def triangles'):helper.index('road=unary_union')])
p=R/'reviews/round-32d-foreground-independent-geometry.json';r=json.loads(p.read_text());reopen=json.loads((R/'reviews/round-32d-reopened-source.json').read_text());cap=reopen['objects']['island_a grass and exposed rock terrain'];cv=np.array(cap['vertices']);half=len(cv)//2;assert np.array_equal(cv[:half,:2],cv[half:,:2]);thickness=cv[:half,2]-cv[half:,2];r['actual_reopened_cap_thickness_min_max_m']=[float(min(thickness)),float(max(thickness))]
tower=next(x for x in r['sites'] if x['site']=='tower');mask=shape(tower['actual_asset_bottom_footprint_geojson']);height=tower['design']['height'];d=glb(R/'captures/foreground_island_study_32d/island_a.glb')['island_a grass and exposed rock terrain'];viol=[];bad=[]
for a in tower['actual_building_bottom_footprint_surface']['bad_clipped_triangles']:
 i=a['triangle'];t=d[i];co=plane(t);inter=Polygon(t[:,:2]).intersection(mask);low=inter.intersection(halfplane(np.array([0,0,height-.001])-co));high=inter.intersection(halfplane(co-np.array([0,0,height+.001])));viol.extend([low,high]);pts=[(float(np.dot(co,[*q,1])-height),list(q)) for q in coords(inter)];pts.sort();native_indices=[j for j,ids in enumerate(cap['triangles']) if tri_key(cv[ids])==tri_key(t)];bad.append({'actual_GLB_triangle':i,'matching_reopened_native_triangles':native_indices,'triangle_xyz':t.tolist(),'full_clipped_patch_area_m2':inter.area,'actual_over1mm_error_area_m2':unary_union([low,high]).area,'worst_xy':pts[0][1],'worst_height_delta_m':pts[0][0]})
r['tower_actual_nonflat_patch_detail']={'method':'Exact actual base-triangle union and clipped linear cap triangle; additional half-plane clipping isolates area over1mm, rather than counting entire affected triangle patch.','actual_area_over1mm_error_m2':unary_union(viol).area,'triangles':bad};r['limits']=[x for x in r['limits'] if 'tree checks are axes' not in x and 'steep locations' not in x];r['limits'].append('Full8pine bottom hexagons checked in round-32d-actual-tree-bases.json using all11meshes; actual runtime transforms/visuals and canopy clearance are separate.');r['pass']=all(x['pass'] for x in r['actual_GLB_mesh_checks']) and all(x['full_design_pad_surface']['pass'] and x['actual_building_bottom_footprint_surface']['pass'] and x['full_design_pad_cap_core_interface']['pass'] and x['actual_asset_footprint_cap_core_interface']['pass'] for x in r['sites']) and r['all8_actual_tree_bases_supported'];r['failure_summary']='Tower exact lowest-bottom triangle footprint extends beyond designed5.1half-width pad; one true footprint patch descends59.6335mm and fails full flat-ground requirement. Coverage and cap/core contact still hold; this is not a floating-tower assertion.';p.write_text(json.dumps(r,indent=2),encoding='utf-8')
md='# 32d 前景A独立几何审查\n\n整体结构门禁未通过：三座建筑的设计pad均平坦，但塔的真实阶梯底面仍有一小片伸出5.1m半宽pad并落在下降坡面上，最大下降59.6335mm，不满足完整塔足迹平坦要求。两屋实际足迹、11件闭合正体积、地坪cap/core接合与8棵完整真实树干底域通过。\n\n## 保存源及实际导出\n\nPID18668结束、文件存在后，独立fresh background Blender打开实际保存源，无builder重跑、无源保存，源SHA不变。11件GLB的实际三角逐坐标等于重开源loop triangles，各有向闭合且正体积。cap2060三角/1032点，core1188三角/596点；3岩肩和5海脚各为独立件。实际cap上下对应点XY完全相同，厚度范围'+str(r['actual_reopened_cap_thickness_min_max_m'])+'m，约0.18m。\n\n## 完整建筑足迹\n\n使用同一冻结keeper_house、实际lighthouse全部节点变换后的最低水平底面三角并集，再应用两屋/塔计划scale与yaw。没有用最低点凸包填入空白区域，也没有只测9个点。\n\n|对象|设计pad面积m²|真实底面面积m²|足迹地面最大误差mm|结论|\n|---|---:|---:|---:|---|\n'
for a in r['sites']:
 q=a['actual_building_bottom_footprint_surface'];md+='|'+a['site']+'|'+f"{a['full_design_pad_surface']['footprint_area_m2']:.6f}|{q['footprint_area_m2']:.6f}|{max(abs(v) for v in q['height_error_min_max_m'])*1000:.6f}|"+('通过' if q['pass'] else '不平坦')+'|\n'
md+='\n塔真实底面48.566508m²中0.027759285m²位于设计pad外；actualGLB cap三角648与真实底面相交片面积0.014907206m²，片内最大下降59.633516mm。进一步线性半平面裁剪，真正超过1mm的面积为'+f"{r['tower_actual_nonflat_patch_detail']['actual_area_over1mm_error_m2']:.9f}"+'m²；实际XYZ、原生对应三角与最差点都在JSON。此处是完整足迹不平坦，不是塔悬空声明；模型底部本来低于实例原点0.5m，实际装配另核验。\n\n三完整设计pad均平坦，所有设计pad及真实资产足迹的cap底/core顶连续覆盖且匹配。地坪通过不能抵消真实塔阶梯伸出部分不平坦。\n\n## 8棵真实pine底域\n\n同一次重开取得全部11网格，再以实际GLB独立计算最高表面。实际pine最低水平面是六边形；按8个计划坐标/scale、无额外yaw，对完整六边形做三角裁剪及上包络比较。8棵底域均连续完整覆盖且平坦（高度变化和内边跳变仅浮点量级），最高表面全部为cap，没有footpath高面。已包含scale1.6大树约1.229784m²完整底域，不是只轴心或六个角点。\n\n实际运行位置、视觉/枝叶净空仍由root核验，不复述运行时9点为完整塔通过。32c仅失败调查，未当成功资产。未做全世界/全岛穷尽自交、C/D隐藏坡、GPU或艺术验收。`pass=false`，`full_reference_accepted=false`。\n';(R/'reviews/round-32d-foreground-independent-geometry.md').write_text(md,encoding='utf-8');print(json.dumps({'pass':r['pass'],'tree_bases':r['all8_actual_tree_bases_supported'],'cap_thickness':r['actual_reopened_cap_thickness_min_max_m'],'tower_detail':r['tower_actual_nonflat_patch_detail']},indent=2))
