from pathlib import Path
import json,math
R=Path(__file__).resolve().parents[1];p=R/'reviews/round-32b-foreground-independent-geometry.json';r=json.loads(p.read_text());r['pass']=all(x['pass'] for x in r['actual_GLB_mesh_checks']) and all(x['full_design_pad_surface']['pass'] and x['actual_building_bottom_footprint_surface']['pass'] and x['full_design_pad_cap_core_interface']['pass'] and x['actual_asset_footprint_cap_core_interface']['pass'] for x in r['sites']);r['all_actual_building_footprints_continuously_supported_and_flat']=all(x['actual_building_bottom_footprint_surface']['pass'] for x in r['sites']);r['all_design_pads_contain_complete_asset_bottoms']=all(x['actual_asset_base_outside_pad_area_m2']<1e-6 for x in r['sites']);r['tower_footprint_clarification']='Tower lowest base includes transformed stair geometry. Exact lowest horizontal triangle union48.5665075m2 extends1.2862447m2 beyond design square; that real extension is fully supported and flat within0.082402mm. Initial conservative vertex convex hull crossed empty regions and yielded1.136mm error; this is superseded by actual bottom-triangle union, not an actual tower-footprint failure. Design-pad containment is diagnostic, not required when actual footprint terrain and interface coverage both pass.';r['limits'][0]='Footprints are exact unions of actual asset lowest-Z horizontal triangles after full glTF scene-node transforms; no roof eaves or convex-hull gap fill. Uniform instance scale and Blender yaw from32bdesign; actual runtime placement pending.'
flags=[]
for a in r['planned_tree_actual_source_rays']:
 if a['highest']:
  slope=math.degrees(math.acos(max(-1,min(1,a['highest']['normal'][2]))));a['highest_slope_deg']=slope
  if slope>40:flags.append({'xy':a['xy'],'height_m':a['highest']['z'],'normal':a['highest']['normal'],'slope_deg':slope,'scope':'Actual axis terrain slope only. Not a generic authored-tree rejection threshold or proof of tree base contact.'})
r['steep_tree_axis_followup']=flags;r['actual_runtime_tree_placement_and_full_base_support_pending']=True;p.write_text(json.dumps(r,indent=2),encoding='utf-8')
md='# 32b 前景A独立几何审查\n\n三座建筑实际足迹与cap/core界面通过；原生11件保存源重开及实际GLB闭合、正体积通过。这里的通过仅覆盖本次几何范围，整体风格仍待实际GPU图。\n\n建模PID34680已结束，正式源/GLB存在后，以独立脚本在fresh background Blender重新打开保存文件；没有重跑builder或保存修改。源SHA保持。11件实际GLB三角与重开源loop triangles逐坐标完全一致，每件有向边闭合、正体积。最小三角面积为core的3.308e-9m²，仍为正；未将闭合当成穷尽自交证明。\n\n|地坪|完整设计pad面积m²|真实底面三角并集m²|真实足迹最大地面高差mm|cap底/core顶最大差mm|\n|---|---:|---:|---:|---:|\n'
for a in r['sites']:
 b=a['actual_building_bottom_footprint_surface'];c=a['actual_asset_footprint_cap_core_interface'];md+='|'+a['site']+'|'+f"{a['full_design_pad_surface']['footprint_area_m2']:.6f}|{b['footprint_area_m2']:.6f}|{max(abs(x) for x in b['height_error_min_max_m'])*1000:.6f}|{max(abs(x) for x in c['cap_bottom_minus_core_top_min_max_m'])*1000:.6f}"+'|\n'
md+='\n上述均为实际三角裁剪得到的完整区域覆盖与线性高度极值，不是9点复述。全部完整设计pad也平坦，最大误差约0.013351mm。三pad及三真实足迹的cap底/core顶连续覆盖，按1mm精度检查通过。\n\n## 塔阶梯足迹与设计pad范围\n\n实际灯塔包含有节点变换的阶梯底面，不能只用半径4.015m圆或忽略节点变换。真实最低底面三角并集48.566508m²，其中1.286245m²在4.25m半宽设计pad之外，但这段实际地面依然完整平坦覆盖，最大差0.082402mm，界面也通过。设计pad不完全包住阶梯是记录项，不等于当前失支承。最初最低点凸包还跨过空白区域，得到约1.136mm差值；已以真实底面三角并集纠正，不能把凸包保守区域当成实际建筑底面失败。\n\n屋资产最低底z=-0.65m，塔最低底z=-0.5m；报告保留这些真实值。运行时origin与模型基础的埋入关系仍应按实际装配记录核验，不在本轮冒称整底面与地面处处共面。\n\n## 八棵树轴的实际源命中\n\n8个计划轴均命中cap最高面，无footpath最高命中。完整高度/法线/三角号在重开报告和主JSON。需要注意：\n\n'
for a in flags:md+='- '+str(a['xy'])+'：z='+f"{a['height_m']:.6f}"+'m，坡度'+f"{a['slope_deg']:.3f}"+'°。\n'
md+='\n这两项是实际坡度提醒，不把任意角度作为美术禁区；尤其(-30,-3)约69.58°，不可在运行时静默过滤或当已验证完整树干支承。树轴检查不是全树底盘/枝叶净空检查。\n\n未执行全世界重复测试、飞行、C/D隐藏背坡或整体风格审查；未扫描三pad之外所有cap/core界面或所有三角自交。`full_reference_accepted=false`。\n';(R/'reviews/round-32b-foreground-independent-geometry.md').write_text(md,encoding='utf-8');print(json.dumps({'pass':r['pass'],'actual_footprints_pass':r['all_actual_building_footprints_continuously_supported_and_flat'],'tower_design_containment':r['all_design_pads_contain_complete_asset_bottoms'],'steep_tree_axes':flags},indent=2))
