from pathlib import Path
R=Path(__file__).resolve().parents[1]
src=(R/'reviews/round-30d-independent-geometry.py').read_text(encoding='utf-8').split('def exposure')[0].replace("P=R/'captures/lantern_island_study_30d';B=R/'captures/lantern_island_study_30c'","P=R/'captures/lantern_island_study_31g';B=R/'captures/lantern_island_study_31f'")
src=src.replace("trees=unary_union([Point(p['xy']).buffer(2) for p in intake['tree_axes']])", "current_bases=json.loads((R/'reviews/round-31f-actual-tree-support.json').read_text())['checks'];trees=unary_union([Polygon(a['actual_trunk_footprint_xy']) for a in current_bases])").replace('current_CD_tree_axis_2m_disks','current_CD_actual_trunk_footprints')
exec(compile(src,'31g_actual_support','exec'))
adj=collections.defaultdict(set)
for a,b in edge:adj[a].add(b);adj[b].add(a)
remaining=set(adj);components=[]
while remaining:
 stack=[remaining.pop()];count=0
 while stack:
  a=stack.pop();count+=1
  for b in adj[a]:
   if b in remaining:remaining.remove(b);stack.append(b)
 components.append(count)
plan=json.loads((P/'reform-plan.json').read_text());cutpath=R/plan['cut_mesh'];assert sha(cutpath)==plan['cut_mesh_sha256'];cut=json.loads(cutpath.read_text());cv=np.array(cut['vertices']);selected=set(plan['selected_faces']);kept=[cv[f] for i,f in enumerate(cut['polygons']) if i not in selected];deleted=[cv[f] for i,f in enumerate(cut['polygons']) if i in selected];lv=np.array(plan['replacement_local_vertices']);lt=np.array(plan['replacement_local_triangles']);replacement=lv[lt];act=counter(ts);assert counter(np.array(kept+list(replacement)))==act
def edgeset(tris):return {tuple(sorted([pointkey(a),pointkey(b)])) for t in tris for a,b in zip(t,np.roll(t,-1,axis=0))}
de=collections.Counter(tuple(sorted([pointkey(a),pointkey(b)])) for t in deleted for a,b in zip(t,np.roll(t,-1,axis=0)));internal={k for k,n in de.items() if n==2};boundary={k for k,n in de.items() if n==1};newedge=edgeset(ts);interior_reappeared=internal&newedge
deleted_counter=counter(np.array(deleted));deleted_survive=deleted_counter&act;repl_counter=counter(replacement);assert len(components)==1
report={'round':'31g','scope':'Actual explicit3D native patch replacement from31f; no same-topology normal inversion or radial-graph assumption. Required support checked with actual trunk footprints, old2m disks excluded as freeze constraints.','files':{str(p.relative_to(R)):sha(p) for p in [P/'island_c.glb',P/'geometry-evidence.json',B/'island_c.glb',cutpath,P/'reform-plan.json']},'native_objects':len(e['new']),'actual_main_triangles':len(ts),'closed_oppositely_paired_edges':True,'connected_components_vertices':components,'minimum_actual_triangle_area_m2':float(min(areas)),'actual_volume_m3':volume,'path_and17rocks_source_exact_actual_triangles_present':preserved,'actual_path_glb_counter_exact':True,'required_supports':supports,'retopology':{'cut_mesh_faces':len(cut['polygons']),'removed_cut_faces':len(deleted),'kept_cut_faces':len(kept),'replacement_faces':len(replacement),'replacement_controls':len(plan['controls']),'actual_kept_plus_replacement_triangle_counter_exact':True,'boundary_vertices':len(plan['boundary']),'boundary_edges_retained':len(boundary&newedge),'boundary_edges_total':len(boundary),'old_interior_edge_count':len(internal),'old_interior_edges_still_in_actual_mesh':len(interior_reappeared),'old_selected_triangles_still_in_actual_mesh':sum(deleted_survive.values()),'all_replacement_triangles_actual':all(act[k]>=n for k,n in repl_counter.items()),'old_interior_vertices_plan':len(plan['interior'])},'base_geometry_and_support_pass':all(s['pass'] for s in supports),'local_triangle_intersection_check_pending':True,'actual_tree_upper_envelope_pending':True,'pass':None,'full_reference_accepted':False,'limits':['Actual tree upper-envelope continuity supplement still required; current masks are exact frozen31f footprint positions, candidate runtime handled by root.','No point-count or topology-change criterion implies art acceptance.','No same-topology normal comparison possible after real replacement.','Fixed boundary proven by actual coordinate edge counters, not only index list.']}
(R/'reviews/round-31g-independent-geometry.json').write_text(json.dumps(report,indent=2),encoding='utf-8');print(json.dumps({k:v for k,v in report.items() if k not in ['files','path_and17rocks_source_exact_actual_triangles_present']},indent=2))
