from pathlib import Path
exec(compile((Path(__file__).parent/'round-29a-independent-geometry.py').read_text().split('old=glb(OLD);')[0],'helpers','exec'))
from shapely.geometry import mapping
planpath=R/'captures/island-30e-faceted-cut-plan.json';plan=json.loads(planpath.read_text());e=json.loads((R/'captures/lantern_island_study_30d/geometry-evidence.json').read_text());loc=json.loads((R/'reviews/round-30d-visible-slope-localization.json').read_text());ind=json.loads((R/'reviews/round-30d-visible-slope-independent.json').read_text());tn='island_c grass and exposed rock terrain';pn='island_c terrain fitted keeper paths'
ob=e['new'][pn];v=np.array(ob['vertices']);road=unary_union([Polygon(v[f,:2]) for f in ob['polygons'] if len(f)==3 and np.cross(v[f[1]]-v[f[0]],v[f[2]]-v[f[0]])[2]>1e-10]);pads=unary_union([Polygon(s['polygon']) for s in e['sites']]);trees=unary_union([Point(p).buffer(2) for p in ind['actual_C_D_tree_local_axes']]);masks={'road':road,'pads':pads,'actual_CD_tree_axis_2m_disks':trees};protect=unary_union(list(masks.values()));rows=[];regions=[]
for c in plan['components']:
 poly=Polygon(c['polygon'],c['holes']);assert poly.is_valid;regions.append(poly);relations={name:{'minimum_distance_m':poly.distance(mask),'intersection_area_m2':poly.intersection(mask).area} for name,mask in masks.items()};margin=poly.distance(protect)
 rows.append({'component':c['name'],'independent_area_m2':poly.area,'minimum_protection_distance_m':margin,'minimum_margin_at_least_0_35m':margin>=.35,'protection':relations,'cdt_point_count':len(c['cdt_points']),'cdt_edge_count':len(c['cdt_edges'])})
union=unary_union(regions);target=[];mv=np.array(e['new'][tn]['vertices'])
for s in loc['samples']:
 point=Point(s['hit_blender_xyz'][:2]);poly=Polygon(mv[e['new'][tn]['polygons'][s['source']['face']],:2]);inside=[]
 for c,region in zip(plan['components'],regions):
  if region.covers(point):
   x,y,z=s['hit_blender_xyz'];floor=float(np.dot(c['floor_plane'],[x,y,1]));inside.append({'component':c['name'],'distance_to_component_boundary_m':point.distance(region.boundary),'ground_z_m':z,'nominal_floor_plane_z_m':floor,'nominal_ground_minus_floor_m':z-floor,'blend_width_m':c['blend_width'],'limitation':'Unblended floor-plane depth only. Native CDT bottom heights and resulting cut depth not yet available.'})
 target.append({'pixel':s['pixel'],'source_face':s['source']['face'],'hit_xyz':s['hit_blender_xyz'],'point_covered_by_cut_projection':union.covers(point),'point_distance_to_cut_projection_m':point.distance(union),'source_face_projection_area_m2':poly.area,'source_face_cut_projection_area_m2':poly.intersection(union).area,'point_distance_to_required_protection_m':point.distance(protect),'candidate_components':inside})
report={'round':'30e_plan','scope':'Bounded independent cutter projection/protection and six actual visible target hit checks. No whole30d geometry/GPU rerun; no final cutter mesh assumed.','files':{str(p.relative_to(R)):sha(p) for p in [planpath,R/'reviews/round-30d-visible-slope-independent.json',R/'captures/lantern_island_study_30d/geometry-evidence.json']},'actual_plan_nominal_margin_m':plan['nominal_protection_margin_m'],'simplification_m':plan['mask_simplification_m'],'components':rows,'six_visible_targets':target,'projection_protection_pass':all(r['minimum_margin_at_least_0_35m'] for r in rows),'actual_bottom_mesh_verified':False,'actual_asset_support_verified':False,'limits':['Nominal floor depth at a target is not the actual native blended cutter-floor height.','Plan projection coverage is neither actual removed volume nor visual success.','Face877 point is close to tree protection; leaving it intact can be intentional if other visible face area is safely cut.','Final Boolean output must preserve support and closed shell without old top-index assumptions.']}
(R/'reviews/round-30e-plan-independent.json').write_text(json.dumps(report,indent=2),encoding='utf-8');print(json.dumps({'components':rows,'targets':target},indent=2))
