from pathlib import Path
import hashlib,json,numpy as np
R=Path(__file__).resolve().parents[2];D=Path(__file__).resolve().parent;E=R/'cloud-evidence/player-nearbay61-renderer-20261001T131646Z-f5163t8s';S=R/'source-assets/coast61-nearbay-flight'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def read(p):return json.loads(Path(p).read_text())
w=read(E/'wrapper-report.json');g=read(E/'images/player-flight-report.json');before=read(E/'input-sha256.json');after=read(E/'output-sha256.json')
assert w['passed'] and w['child_exit_code']==0 and w['sources_unchanged'] and not w['logged_errors'];assert g['passed'] and g['complete'] and not g['failures'] and all(c['passed']for c in g['checks']);assert before==after and len(before)==1477 and all(sha(p)==h for p,h in before.items())
assert len(g['captures'])==5 and all(sha(c['path'])==c['sha256']for c in g['captures'])
origin=np.array(g['flight_start']['position']);end=np.array(g['stop']['position']);forward=np.array([120.,0.,180.]);forward/=np.linalg.norm(forward);steps=np.array([x['step_m']for x in g['samples']]);along=float((end-origin)@forward)
assert np.array_equal(origin,[-3480.,18.,-3740.]);assert np.max(abs(steps.sum(0)-(end-origin)))<1e-9
recomputed_path=float(np.linalg.norm(steps,axis=1).sum());assert abs(recomputed_path-g['path_m'])<1e-6
assert 195<=along<=216.33307652783935 and len(g['samples'])==544 and g['all_keys_released']
pose_rows=[x for x in g['inherited_pose_transitions']if 'camera_actual_hex'in x];assert len(pose_rows)==4 and all(x['passed'] and x['camera_actual_hex']==x['camera_expected_hex']and x['ship_actual_hex']==x['ship_expected_hex']for x in pose_rows)
assert len(g['preflight']['queries'])==86 and all(x['clear']for x in g['preflight']['queries']);assert len(g['preflight']['combined_body_queries'])==12 and all(not x['blocked'] and x['contacts']==0 for x in g['preflight']['combined_body_queries'])
result={'passed':True,'review':'Finished actual evidence only, no rerun','evidence':str(E.relative_to(R)),'wrapper_sha256':sha(E/'wrapper-report.json'),'runtime_report_sha256':sha(E/'images/player-flight-report.json'),'source_count':1477,'all_current_sources_match':True,'input_check_count':len(g['checks']),'real_physics_samples':544,'initial_fixture':origin.tolist(),'fixture_excluded_from_distance':True,'final_stop':end.tolist(),'horizontal_along_corridor_m':along,'horizontal_chord_m':float(np.linalg.norm((end-origin)[[0,2]])),'three_dimensional_endpoint_chord_m':float(np.linalg.norm(end-origin)),'actual_three_dimensional_integrated_path_m':g['path_m'],'independently_recomputed_path_m':recomputed_path,'sum_of_steps_matches_endpoint_delta_max_m':float(np.max(abs(steps.sum(0)-(end-origin)))),'max_lateral_drift_m':max(x['lateral_m']for x in g['samples']),'max_step_velocity_difference_m':g['max_displacement_velocity_error_m'],'actual_height_levels_m':g['altitude_levels_m'],'actual_physics_seconds':g['sim_seconds'],'peak_speed_mps':g['peak_speed_mps'],'five_actual_image_hashes_passed':True,'actual_physics_preflight_shape_sweeps':86,'actual_combined_body_test_move_queries':12,'actual_visible_meshes':g['preflight']['visible_mesh_count'],'propeller_full_rotation_meshes':g['preflight']['full_revolution_propeller_mesh_count'],'conservative_min_sea_clearance_m':g['preflight']['minimum_sea_clearance_from_conservative_visual_bounds_m'],'pre_and_post_native_observation_exact_pose_comparisons':4,'all_exact_pose_comparisons_passed':True,'pose_attribution':'No exact-pose mismatch reproduced in this one fixture/native-flight/native observe_reference-method plus physical F2 sequence. No camera restoration or expectation change was used. This does not establish every repeated GUI sequence is drift-free.','process_seconds':w['wall_seconds'],'max_rss_kib':w['child_max_rss_kib'],'limits':['216.33m is prechecked corridor length; actual horizontal progress is202.391m and actual3D travelled path is211.009m','The one-time initial fixture and later reference-method navigation are never counted as flown distance','Native physical input events and observe_reference method calls are tested; GUI clicks, external keyboard focus and all user navigation sequences are not','llvmpipe software rendering; no hardware GPU, full-world route or reference visual acceptance','Current inputs remain unchanged; no native scene/default write and no extra engine run in review']}
(D/'review.json').write_text(json.dumps(result,indent=2)+'\n');(S/'verified-flight61.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
