import json,hashlib,re,collections
from pathlib import Path
ROOT=Path('/workspace/scratch/a29d03198654/Aether');D=ROOT/'source-assets/lake-rim53';O=D/'integration-west53';P=ROOT/'candidates/round40-exclusive-20260930/project'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
payload=json.load(open(O/'integration-payload.json'))
payload['source_metadata']={'design':'West-only53d source integration; existing340-triangle root retained exactly, four new closed components','source_payload':str(D/'revision-d/rim53-payload.json'),'source_payload_sha256':sha(D/'revision-d/rim53-payload.json'),'scope':'One mountain family and exact120 scatter translation slots; no other source family, terrain, camera, sky, water, material or default-scene modification','status':'Integration preparation only; source five-view reviewed for limited integration only'}
json.dump(payload,open(O/'integration-payload.json','w'))
base=json.load(open(D/'base51b.json'));report=json.load(open(O/'scatter-reconcile-report.json'));groups=collections.defaultdict(list)
for e in payload['scatter']:groups[e['node_path']].append(e['index'])
inputs=[D/'revision-d/massif_west_spur_rim53.blend',D/'revision-d/massif_west_spur_rim53.glb',D/'revision-d/rim53-payload.json',D/'revision-d/sculpt-report.json',D/'revision-d/native-readback-impact.json',D/'revision-d/root-join-check.json',D/'revision-d/continuous-water-footprint-proof.json',D/'base51b.json',O/'integration-payload.json',O/'scatter-reconcile-report.json',O/'west53_audit.gd',O/'build_west53.gd',O/'source-visual-gate.json',O/'runtime-probes.json',P/'scenes/candidate51b/build-report-51b.json']
ledger=json.load(open(P/'scenes/candidate51b/build-report-51b.json'));materials=set(row['new_material_path'] for row in ledger['material_ledger']);shaders=set()
for res in sorted(materials):
 path=P/res.removeprefix('res://');inputs.append(path)
 for shader in re.findall(r'\[ext_resource type="Shader" path="([^"]+)"',path.read_text()):shaders.add(shader)
inputs.extend(P/res.removeprefix('res://') for res in sorted(shaders))
manifest={'schema_version':1,'baseline_scene':'res://scenes/candidate51b/Game51b.tscn','baseline_sha256':payload['baseline_sha256'],'candidate_scene':'res://scenes/candidate53d-west/Game53dWest.tscn','source_payload_path':str(D/'revision-d/rim53-payload.json'),'source_payload_sha256':sha(D/'revision-d/rim53-payload.json'),'source_form_visual_gate':'ready for limited west-only trial; reference visual acceptance false','immutable_inputs':[{'path':str(p),'sha256':sha(p)} for p in inputs],'original_root_policy':'retain exact existing ArrayMesh including vertex positions,colors,normals,flags and all original material fields','added_mesh_nodes':['World/Mountains/massif_west_spur/Model/'+p for p in ['ridge_shoulders','snow_cap','snow_gully','shore_rock_apron']],'changed_collision_node':'World/Mountains/massif_west_spur/Collision/Shape','collision_policy':'duplicate existing shape properties and replace only data with joined actual five-mesh faces; retain layer5/mask2','scatter_groups':{p:sorted(indices) for p,indices in groups.items()},'all_six_tile_scatter_counts':{g['node'].removeprefix('/Skyfarer/'):g['count'] for g in base['scatter']},'scatter_counts':report['scatter_counts'],'retained_material_count':len(materials),'retained_shader_count':len(shaders),'retained_original_binding_rows':len(ledger['binding_ledger']),'new_material_binding':'res://assets/reflection51b/clip_material_005.tres','new_binding_fields_per_added_mesh':['material_override','surface_material_override/0','mesh_surface_material/0'],'water_proof':json.load(open(D/'revision-d/continuous-water-footprint-proof.json')),'root_proof':json.load(open(D/'revision-d/root-join-check.json')),'forbidden_source_families':['massif_cirque_wall','massif_east_foothill','massif_frost_crown'],'visual_acceptance':False,'saved_scene_exists':False}
json.dump(manifest,open(O/'integration-manifest.json','w'),indent=2)
print('MANIFEST',len(inputs),'immutable inputs',len(materials),'materials',len(shaders),'shaders',len(payload['scatter']),'scatter edits',len(groups),'groups')
